# Generated by Django 5.2.6 on 2025-09-16 06:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rb_core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collaboration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('revenue_split', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('active', 'Active')], max_length=20)),
                ('collaborators', models.ManyToManyField(related_name='joined_collabs', to='rb_core.user')),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rb_core.content')),
                ('initiators', models.ManyToManyField(related_name='initiated_collabs', to='rb_core.user')),
            ],
        ),
    ]
