# Generated by Django 5.2.6 on 2025-09-20 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rb_core', '0002_collaboration'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='flagged',
            field=models.BooleanField(default=False),
        ),
    ]
