# Generated by Django 5.2.6 on 2025-09-20 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rb_core', '0003_content_flagged'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='content_type',
            field=models.CharField(choices=[('book', 'Book'), ('art', 'Art'), ('film', 'Film'), ('music', 'Music')], default='book', max_length=16),
        ),
        migrations.AddField(
            model_name='content',
            name='genre',
            field=models.CharField(choices=[('fantasy', 'Fantasy'), ('scifi', 'Sci-Fi'), ('nonfiction', 'Non-Fiction'), ('drama', 'Drama'), ('comedy', 'Comedy'), ('other', 'Other')], default='other', max_length=32),
        ),
    ]
