# Generated by Django 5.2.6 on 2025-09-22 05:22

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rb_core', '0004_content_content_type_content_genre'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, unique=True, validators=[django.core.validators.RegexValidator(message='Username may only contain letters, numbers, and underscores (max 50).', regex='^[A-Za-z0-9_]{1,50}$')])),
                ('display_name', models.CharField(blank=True, default='', max_length=100)),
                ('email_hash', models.CharField(blank=True, default='', max_length=64)),
                ('wallet_address', models.CharField(blank=True, default='', max_length=44)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='rb_core.user')),
            ],
        ),
    ]
