# Generated by Django 5.2.6 on 2025-09-22 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rb_core', '0005_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='wallet_address',
            field=models.CharField(blank=True, default=None, max_length=44, null=True, unique=True),
        ),
    ]
