# Generated by Django 5.2.6 on 2025-09-24 05:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rb_core', '0006_alter_userprofile_wallet_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='wallet_address',
        ),
    ]
