# Generated by Django 5.2.6 on 2025-09-24 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rb_core', '0007_remove_user_wallet_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='avatar_url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='banner_url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='genres',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='location',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='roles',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
