# Generated by Django 5.2.6 on 2025-09-29 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rb_core', '0008_userprofile_avatar_url_userprofile_banner_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='avatar_image',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='banner_image',
            field=models.ImageField(blank=True, null=True, upload_to='banners/'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='content_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='fee_bps',
            field=models.PositiveIntegerField(default=1000),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='tier',
            field=models.CharField(choices=[('Basic', 'Basic'), ('Pro', 'Pro'), ('Elite', 'Elite')], default='Basic', max_length=16),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='total_sales_usd',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
