# Generated by Django 5.2.6 on 2025-09-29 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rb_core', '0009_userprofile_avatar_image_userprofile_banner_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_private',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='status',
            field=models.CharField(choices=[('Mint-Ready Partner', 'Mint-Ready Partner'), ('Chain Builder', 'Chain Builder'), ('Open Node', 'Open Node'), ('Selective Forge', 'Selective Forge'), ('Linked Capacity', 'Linked Capacity'), ('Partial Protocol', 'Partial Protocol'), ('Locked Chain', 'Locked Chain'), ('Sealed Vault', 'Sealed Vault'), ('Exclusive Mint', 'Exclusive Mint')], default='Open Node', max_length=32),
        ),
    ]
