# Generated by Django 5.2.6 on 2025-09-30 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rb_core', '0010_userprofile_is_private_userprofile_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='editions',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='content',
            name='price_usd',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='content',
            name='teaser_percent',
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.AddField(
            model_name='content',
            name='watermark_preview',
            field=models.BooleanField(default=False),
        ),
    ]
