# Generated by Django 5.2.6 on 2025-09-30 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rb_core', '0011_content_editions_content_price_usd_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='inventory_status',
            field=models.CharField(choices=[('draft', 'Draft'), ('minted', 'Minted')], default='draft', max_length=16),
        ),
    ]
