# Generated by Django 5.2.6 on 2025-10-01 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rb_core', '0012_content_inventory_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestFeeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
