# Generated by Django 5.2.6 on 2025-10-18 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rb_core', '0013_testfeelog'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='teaser_html',
            field=models.TextField(blank=True, default=''),
        ),
    ]
