# Generated by Django 5.2.6 on 2025-10-19 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rb_core', '0014_content_teaser_html'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='web3auth_sub',
            field=models.CharField(blank=True, default=None, max_length=128, null=True, unique=True),
        ),
    ]
