# Generated by Django 5.2.6 on 2025-10-24 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rb_core', '0016_bookproject_chapter'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookproject',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='book_covers/'),
        ),
    ]
