# Generated by Django 5.2.6 on 2025-10-24 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rb_core', '0017_bookproject_cover_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatar_image',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='avatars/'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='banner_image',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='banners/'),
        ),
    ]
