# Generated by Django 5.2.6 on 2025-10-31 04:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rb_core', '0018_alter_userprofile_avatar_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_price_usd', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stripe_fee_usd', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('platform_fee_usd', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('creator_earnings_usd', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('stripe_payment_intent_id', models.CharField(max_length=255, unique=True)),
                ('stripe_checkout_session_id', models.CharField(blank=True, default='', max_length=255, unique=True)),
                ('transaction_signature', models.CharField(blank=True, default='', max_length=128)),
                ('nft_minted', models.BooleanField(default=False)),
                ('nft_mint_eligible_at', models.DateTimeField(blank=True, null=True)),
                ('purchased_at', models.DateTimeField(auto_now_add=True)),
                ('refunded', models.BooleanField(default=False)),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchases', to='rb_core.content')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-purchased_at'],
                'indexes': [models.Index(fields=['user', 'content'], name='rb_core_pur_user_id_9e19a1_idx'), models.Index(fields=['stripe_payment_intent_id'], name='rb_core_pur_stripe__bcf16c_idx')],
            },
        ),
    ]
