# Generated by Django 5.2.6 on 2025-11-03 05:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rb_core', '0020_readingprogress'),
    ]

    operations = [
        migrations.CreateModel(
            name='CollaborativeProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content_type', models.CharField(choices=[('book', 'Book'), ('music', 'Music'), ('video', 'Video'), ('art', 'Art')], max_length=16)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('ready_for_mint', 'Ready for Mint'), ('minted', 'Minted'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('milestones', models.JSONField(default=list, help_text='Milestone definitions and tracking')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(help_text='Project initiator', on_delete=django.db.models.deletion.CASCADE, related_name='created_projects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_type', models.CharField(choices=[('text', 'Text'), ('image', 'Image'), ('audio', 'Audio'), ('video', 'Video')], max_length=16)),
                ('title', models.CharField(blank=True, max_length=200)),
                ('content_html', models.TextField(blank=True, help_text='For text sections')),
                ('media_file', models.FileField(blank=True, help_text='For image, audio, or video sections', null=True, upload_to='collaborative_content/')),
                ('order', models.IntegerField(default=0, help_text='Display order within project')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(help_text='Collaborator who can edit this section', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='rb_core.collaborativeproject')),
            ],
            options={
                'ordering': ['order', 'created_at'],
                'unique_together': {('project', 'order')},
            },
        ),
        migrations.CreateModel(
            name='ProjectComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('resolved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('parent_comment', models.ForeignKey(blank=True, help_text='For threaded discussions', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='rb_core.projectcomment')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='rb_core.collaborativeproject')),
                ('section', models.ForeignKey(blank=True, help_text='Optional: specific section this comment refers to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='rb_core.projectsection')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CollaboratorRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(help_text='Author, Illustrator, Musician, Editor, etc.', max_length=50)),
                ('revenue_percentage', models.DecimalField(decimal_places=2, help_text='Revenue share percentage (0.00 to 100.00)', max_digits=5)),
                ('invited_at', models.DateTimeField(auto_now_add=True)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('invited', 'Invited'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('exited', 'Exited')], default='invited', max_length=20)),
                ('can_edit_text', models.BooleanField(default=False)),
                ('can_edit_images', models.BooleanField(default=False)),
                ('can_edit_audio', models.BooleanField(default=False)),
                ('can_edit_video', models.BooleanField(default=False)),
                ('approved_current_version', models.BooleanField(default=False)),
                ('approved_revenue_split', models.BooleanField(default=False)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collaborators', to='rb_core.collaborativeproject')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collaborations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-revenue_percentage'],
                'unique_together': {('project', 'user')},
            },
        ),
    ]
