# Generated by Django 5.2.6 on 2025-11-03 18:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rb_core', '0021_collaborativeproject_projectsection_projectcomment_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('invitation', 'Collaboration Invitation'), ('invitation_response', 'Invitation Response'), ('comment', 'Comment'), ('approval', 'Approval Status Change'), ('section_update', 'Section Update'), ('revenue_proposal', 'Revenue Split Proposal'), ('mint_ready', 'Project Ready for Minting')], db_index=True, max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('action_url', models.CharField(blank=True, default='', help_text='URL to navigate to when notification is clicked', max_length=255)),
                ('read', models.BooleanField(db_index=True, default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('from_user', models.ForeignKey(help_text='User who triggered this notification', on_delete=django.db.models.deletion.CASCADE, related_name='sent_notifications', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(blank=True, help_text='Related collaborative project', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='rb_core.collaborativeproject')),
                ('recipient', models.ForeignKey(help_text='User who receives this notification', on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipient', 'read', '-created_at'], name='rb_core_not_recipie_dfc0c5_idx'), models.Index(fields=['recipient', '-created_at'], name='rb_core_not_recipie_27a619_idx')],
            },
        ),
    ]
