# Generated by Django 5.2.6 on 2025-11-09 06:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rb_core', '0022_notification'),
    ]

    operations = [
        migrations.CreateModel(
            name='BetaInvite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('invite_code', models.CharField(blank=True, max_length=32, unique=True)),
                ('status', models.CharField(choices=[('requested', 'Requested'), ('approved', 'Approved'), ('sent', 'Invite Sent'), ('used', 'Account Created'), ('declined', 'Declined')], db_index=True, default='requested', max_length=20)),
                ('message', models.TextField(blank=True, help_text='Why they want access')),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CommentAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='comment_attachments/%Y/%m/')),
                ('filename', models.CharField(max_length=255)),
                ('file_size', models.IntegerField(help_text='File size in bytes')),
                ('file_type', models.CharField(help_text='MIME type', max_length=100)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='CommentReaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emoji', models.CharField(choices=[('👍', 'Thumbs Up'), ('👎', 'Thumbs Down'), ('❤️', 'Heart'), ('😊', 'Smile'), ('😂', 'Laugh'), ('🎉', 'Party'), ('🚀', 'Rocket'), ('👀', 'Eyes')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='projectcomment',
            name='edit_history',
            field=models.JSONField(blank=True, default=list, help_text='History of edits with timestamps and previous content'),
        ),
        migrations.AddField(
            model_name='projectcomment',
            name='edited',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='projectcomment',
            name='mentions',
            field=models.ManyToManyField(blank=True, help_text='Users mentioned in this comment with @username', related_name='mentioned_in_comments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='projectcomment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddIndex(
            model_name='projectcomment',
            index=models.Index(fields=['project', '-created_at'], name='rb_core_pro_project_426665_idx'),
        ),
        migrations.AddIndex(
            model_name='projectcomment',
            index=models.Index(fields=['section', '-created_at'], name='rb_core_pro_section_6d4faf_idx'),
        ),
        migrations.AddIndex(
            model_name='projectcomment',
            index=models.Index(fields=['parent_comment', '-created_at'], name='rb_core_pro_parent__a101d7_idx'),
        ),
        migrations.AddField(
            model_name='betainvite',
            name='invited_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='beta_invites_sent', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='commentattachment',
            name='comment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='rb_core.projectcomment'),
        ),
        migrations.AddField(
            model_name='commentattachment',
            name='uploaded_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='commentreaction',
            name='comment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='rb_core.projectcomment'),
        ),
        migrations.AddField(
            model_name='commentreaction',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='betainvite',
            index=models.Index(fields=['status', '-created_at'], name='rb_core_bet_status_3d4237_idx'),
        ),
        migrations.AddIndex(
            model_name='betainvite',
            index=models.Index(fields=['invite_code'], name='rb_core_bet_invite__0b260d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='commentreaction',
            unique_together={('comment', 'user', 'emoji')},
        ),
    ]
