# Generated by Django 5.2.6 on 2025-11-09 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rb_core', '0023_betainvite_commentattachment_commentreaction_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='betainvite',
            name='invite_code',
            field=models.CharField(blank=True, max_length=32, null=True, unique=True),
        ),
    ]
