# Generated by Django 5.2.6 on 2025-11-18 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rb_core', '0024_alter_betainvite_invite_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='creator_amount',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='90% of net_after_costs', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='purchase',
            name='gross_amount',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='What customer paid', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='purchase',
            name='mint_cost',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='ACTUAL gas cost from blockchain transaction', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='purchase',
            name='net_after_costs',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Net after Stripe AND gas', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='purchase',
            name='net_after_stripe',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Gross - Stripe fee', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='purchase',
            name='nft_mint_address',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='purchase',
            name='platform_fee',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='10% of net_after_costs', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='purchase',
            name='status',
            field=models.CharField(choices=[('payment_pending', 'Payment Pending'), ('payment_completed', 'Payment Completed'), ('minting', 'Minting NFT'), ('completed', 'Completed'), ('failed', 'Failed'), ('refunded', 'Refunded')], default='payment_pending', max_length=20),
        ),
        migrations.AddField(
            model_name='purchase',
            name='stripe_balance_txn_id',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='purchase',
            name='stripe_charge_id',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='purchase',
            name='stripe_fee',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='ACTUAL fee from Stripe balance_transaction', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='purchase',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='stripe_checkout_session_id',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddIndex(
            model_name='purchase',
            index=models.Index(fields=['status'], name='rb_core_pur_status_628853_idx'),
        ),
    ]
