# Generated by Django 5.2.6 on 2025-11-27 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rb_core', '0029_add_circle_w3s_fields'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='purchase',
            name='rb_core_pur_usdc_pa_idx',
        ),
        migrations.RemoveIndex(
            model_name='purchase',
            name='rb_core_pur_circle_nft_idx',
        ),
        migrations.RenameIndex(
            model_name='purchase',
            new_name='rb_core_pur_circle__30bd57_idx',
            old_name='rb_core_pur_circle_p_idx',
        ),
        migrations.RenameIndex(
            model_name='purchase',
            new_name='rb_core_pur_payment_2aa7d0_idx',
            old_name='rb_core_pur_payment_p_idx',
        ),
        migrations.RenameIndex(
            model_name='readingprogress',
            new_name='rb_core_rea_user_id_4b6f55_idx',
            old_name='rb_core_rea_user_co_idx',
        ),
        migrations.RenameIndex(
            model_name='readingprogress',
            new_name='rb_core_rea_user_id_3ffc14_idx',
            old_name='rb_core_rea_user_la_idx',
        ),
        migrations.AlterField(
            model_name='purchase',
            name='circle_fee',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Circle processing fee in USD', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='net_after_circle',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Net amount after Circle fees (gross - circle_fee)', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='payment_provider',
            field=models.CharField(choices=[('stripe', 'Stripe'), ('circle', 'Circle')], default='stripe', help_text='Payment provider used for this purchase', max_length=20),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='stripe_payment_intent_id',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
