# Generated by Django 5.2.6 on 2025-11-27 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rb_core', '0030_remove_purchase_rb_core_pur_usdc_pa_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='circle_user_id',
            field=models.CharField(
                max_length=128,
                unique=True,
                null=True,
                blank=True,
                default=None,
                help_text='Circle user account ID for user-controlled wallet system'
            ),
        ),
    ]
