# Generated by Django 5.2.6 on 2025-11-27 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rb_core', '0031_add_circle_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='wallet_provider',
            field=models.CharField(blank=True, choices=[('circle_user_controlled', 'Circle User-Controlled Wallet'), ('circle_w3s', 'Circle Web3 Services'), ('external', 'External Wallet'), ('web3auth', 'Web3Auth (Deprecated)')], default='circle_user_controlled', max_length=30),
        ),
    ]
