# Generated by Django 5.2.6 on 2025-12-04 05:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rb_core', '0032_update_wallet_provider'),
    ]

    operations = [
        migrations.CreateModel(
            name='CollaboratorPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collaborator_wallet', models.CharField(max_length=255)),
                ('amount_usdc', models.DecimalField(decimal_places=6, max_digits=10)),
                ('percentage', models.IntegerField(help_text='Revenue percentage (e.g., 40 for 40%)')),
                ('role', models.CharField(blank=True, help_text='Collaborator role (writer, artist, editor, etc.)', max_length=50, null=True)),
                ('paid_at', models.DateTimeField(auto_now_add=True)),
                ('transaction_signature', models.CharField(help_text='Solana transaction signature (same for all collaborators in atomic tx)', max_length=255)),
            ],
            options={
                'ordering': ['-paid_at'],
            },
        ),
        migrations.CreateModel(
            name='TreasuryReconciliation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_start', models.DateTimeField()),
                ('week_end', models.DateTimeField()),
                ('purchases_count', models.IntegerField()),
                ('total_usdc_fronted', models.DecimalField(decimal_places=6, help_text='Total USDC fronted from treasury this week', max_digits=12)),
                ('platform_fees_earned', models.DecimalField(decimal_places=6, help_text='Total platform fees (10%) earned this week', max_digits=12)),
                ('net_usdc_to_replenish', models.DecimalField(decimal_places=6, help_text='Net USDC needed to replenish (fronted - fees)', max_digits=12)),
                ('stripe_balance_usd', models.DecimalField(blank=True, decimal_places=2, help_text='Stripe balance in USD at reconciliation time', max_digits=12, null=True)),
                ('replenishment_status', models.CharField(choices=[('pending', 'Pending Manual Replenishment'), ('in_progress', 'ACH Transfer In Progress'), ('completed', 'Completed')], default='pending', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.RemoveIndex(
            model_name='purchase',
            name='rb_core_pur_circle__30bd57_idx',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='circle_fee',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='circle_mint_transaction_id',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='circle_nft_id',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='circle_payment_id',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='circle_tracking_ref',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='net_after_circle',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='usdc_amount',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='usdc_payment_status',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='usdc_transfer_signature',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='circle_user_id',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='circle_wallet_address',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='circle_wallet_id',
        ),
        migrations.AddField(
            model_name='purchase',
            name='distribution_details',
            field=models.JSONField(blank=True, default=dict, help_text='Breakdown of USDC distribution to collaborators'),
        ),
        migrations.AddField(
            model_name='purchase',
            name='platform_usdc_earned',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Platform 10% fee in USDC (stays in treasury)', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='purchase',
            name='platform_usdc_fronted',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Total USDC fronted from platform treasury for this purchase', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='purchase',
            name='usdc_distribution_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', help_text='Status of atomic USDC distribution', max_length=20),
        ),
        migrations.AddField(
            model_name='purchase',
            name='usdc_distribution_transaction',
            field=models.CharField(blank=True, help_text='Solana transaction signature for atomic USDC distribution', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='usdc_distributed_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp of atomic USDC distribution', null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='wallet_provider',
            field=models.CharField(blank=True, choices=[('web3auth', 'Web3Auth'), ('external', 'External Wallet')], default='web3auth', max_length=30),
        ),
        migrations.AddField(
            model_name='collaboratorpayment',
            name='collaborator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='collaboratorpayment',
            name='purchase',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collaborator_payments', to='rb_core.purchase'),
        ),
        migrations.AlterUniqueTogether(
            name='collaboratorpayment',
            unique_together={('purchase', 'collaborator')},
        ),
    ]
