# Generated by Django 5.2.6 on 2025-12-04 05:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rb_core', '0033_remove_circle_add_atomic_usdc'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='chapter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='purchases', to='rb_core.chapter'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='content',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='purchases', to='rb_core.content'),
        ),
    ]
