# Generated by Django 5.2.6 on 2025-12-05 04:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rb_core', '0034_add_chapter_to_purchase'),
    ]

    operations = [
        migrations.CreateModel(
            name='CollaboratorApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approved', models.BooleanField(help_text='True if approved, False if rejected')),
                ('response_note', models.TextField(blank=True, default='', help_text='Optional note from collaborator')),
                ('responded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-responded_at'],
            },
        ),
        migrations.CreateModel(
            name='DelistApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField(help_text='Reason for delisting (visible to all collaborators)')),
                ('status', models.CharField(choices=[('pending', 'Pending Approval'), ('approved', 'Approved (Delisted)'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('resolved_at', models.DateTimeField(blank=True, help_text='Timestamp when all approvals received or request was rejected', null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='chapter',
            name='delisted_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when chapter was delisted from marketplace', null=True),
        ),
        migrations.AddField(
            model_name='chapter',
            name='delisted_by',
            field=models.ForeignKey(blank=True, help_text='User who delisted this chapter', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delisted_chapters', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='chapter',
            name='delisted_reason',
            field=models.TextField(blank=True, default='', help_text='Reason for delisting (visible to collaborators)'),
        ),
        migrations.AddField(
            model_name='chapter',
            name='is_listed',
            field=models.BooleanField(db_index=True, default=True, help_text='Whether this chapter is visible in the marketplace (default: True)'),
        ),
        migrations.AddIndex(
            model_name='chapter',
            index=models.Index(fields=['is_listed', '-created_at'], name='rb_core_cha_is_list_83fd83_idx'),
        ),
        migrations.AddIndex(
            model_name='chapter',
            index=models.Index(fields=['book_project', 'is_listed'], name='rb_core_cha_book_pr_bd4d85_idx'),
        ),
        migrations.AddField(
            model_name='collaboratorapproval',
            name='collaborator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delist_responses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='delistapproval',
            name='chapter',
            field=models.ForeignKey(help_text='Chapter to be delisted', on_delete=django.db.models.deletion.CASCADE, related_name='delist_requests', to='rb_core.chapter'),
        ),
        migrations.AddField(
            model_name='delistapproval',
            name='requested_by',
            field=models.ForeignKey(help_text='Collaborator who initiated the delist request', on_delete=django.db.models.deletion.CASCADE, related_name='delist_requests_initiated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='collaboratorapproval',
            name='delist_request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collaborator_responses', to='rb_core.delistapproval'),
        ),
        migrations.AddIndex(
            model_name='delistapproval',
            index=models.Index(fields=['chapter', 'status'], name='rb_core_del_chapter_603a3c_idx'),
        ),
        migrations.AddIndex(
            model_name='delistapproval',
            index=models.Index(fields=['status', '-created_at'], name='rb_core_del_status_d0a00e_idx'),
        ),
        migrations.AddIndex(
            model_name='collaboratorapproval',
            index=models.Index(fields=['delist_request', 'approved'], name='rb_core_col_delist__2d2875_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='collaboratorapproval',
            unique_together={('delist_request', 'collaborator')},
        ),
    ]
