# Generated by Django 5.2.6 on 2025-12-08 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rb_core', '0035_collaboratorapproval_delistapproval_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='buyer_total',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Total amount buyer paid (chapter_price + credit_card_fee)', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='purchase',
            name='chapter_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="Chapter's list price (what creator set)", max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='purchase',
            name='credit_card_fee',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Fee passed to buyer for credit card processing', max_digits=10, null=True),
        ),
    ]
