# Generated by Django 5.2.6 on 2025-12-11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rb_core', '0036_add_cc_fee_passthrough_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='price',
            field=models.DecimalField(
                decimal_places=2,
                default=1.00,
                help_text='Price in USD for purchasing this chapter',
                max_digits=10,
            ),
        ),
    ]
