# Generated by Django 5.2.6 on 2025-12-11 23:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rb_core', '0037_add_chapter_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='collaboratorrole',
            name='can_invite_others',
            field=models.BooleanField(default=False, help_text='Can invite additional collaborators to the project'),
        ),
        migrations.AddField(
            model_name='collaboratorrole',
            name='counter_message',
            field=models.TextField(blank=True, help_text='Message explaining the counter-proposal'),
        ),
        migrations.AddField(
            model_name='collaboratorrole',
            name='deadline_extended_at',
            field=models.DateTimeField(blank=True, help_text='When deadline was last extended', null=True),
        ),
        migrations.AddField(
            model_name='collaboratorrole',
            name='deadline_extension_reason',
            field=models.TextField(blank=True, help_text='Reason for deadline extension'),
        ),
        migrations.AddField(
            model_name='collaboratorrole',
            name='delivery_deadline',
            field=models.DateTimeField(blank=True, help_text='Deadline for collaborator to complete their sections', null=True),
        ),
        migrations.AddField(
            model_name='collaboratorrole',
            name='is_lead',
            field=models.BooleanField(default=False, help_text='Lead collaborator with additional permissions'),
        ),
        migrations.AddField(
            model_name='collaboratorrole',
            name='proposed_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Counter-proposed revenue percentage', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='collaboratorrole',
            name='sections_due',
            field=models.JSONField(blank=True, default=list, help_text='List of section IDs the collaborator is responsible for'),
        ),
        migrations.AddField(
            model_name='collaboratorrole',
            name='voting_weight',
            field=models.IntegerField(default=1, help_text='Weight of vote in proposals (default 1)'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('invitation', 'Collaboration Invitation'), ('invitation_response', 'Invitation Response'), ('counter_proposal', 'Counter Proposal'), ('comment', 'Comment'), ('approval', 'Approval Status Change'), ('section_update', 'Section Update'), ('revenue_proposal', 'Revenue Split Proposal'), ('mint_ready', 'Project Ready for Minting')], db_index=True, max_length=20),
        ),
        migrations.CreateModel(
            name='Proposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proposal_type', models.CharField(choices=[('revenue_split', 'Revenue Split Change'), ('new_member', 'Invite New Collaborator'), ('remove_member', 'Remove Collaborator'), ('project_change', 'Project Change'), ('deadline_extension', 'Deadline Extension'), ('exit_collaborator', 'Exit Collaborator')], max_length=30)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('proposal_data', models.JSONField(default=dict, help_text='JSON data containing the actual proposal content')),
                ('status', models.CharField(choices=[('pending', 'Pending Votes'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('voting_threshold', models.CharField(choices=[('majority', 'Majority (>50%)'), ('unanimous', 'Unanimous (100%)'), ('owner_decides', 'Owner Decides')], default='majority', max_length=20)),
                ('expires_at', models.DateTimeField(blank=True, help_text='When the proposal expires if not enough votes', null=True)),
                ('resolved_at', models.DateTimeField(blank=True, help_text='When the proposal was approved/rejected', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposals', to='rb_core.collaborativeproject')),
                ('proposer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposals_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CollaboratorRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quality_score', models.IntegerField(help_text='Quality of work (1-5)')),
                ('deadline_score', models.IntegerField(help_text='Meeting deadlines (1-5)')),
                ('communication_score', models.IntegerField(help_text='Communication quality (1-5)')),
                ('would_collab_again', models.IntegerField(help_text='Would collaborate again (1-5)')),
                ('private_note', models.TextField(blank=True, help_text='Private note only visible to rated user')),
                ('public_feedback', models.TextField(blank=True, help_text='Public feedback visible on profile')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='rb_core.collaborativeproject')),
                ('rated_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings_received', to=settings.AUTH_USER_MODEL)),
                ('rater', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings_given', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('project', 'rater', 'rated_user')},
            },
        ),
        migrations.CreateModel(
            name='ProposalVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote', models.CharField(choices=[('approve', 'Approve'), ('reject', 'Reject'), ('abstain', 'Abstain')], max_length=10)),
                ('comment', models.TextField(blank=True, help_text='Optional comment explaining the vote')),
                ('voted_at', models.DateTimeField(auto_now_add=True)),
                ('proposal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='rb_core.proposal')),
                ('voter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposal_votes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-voted_at'],
                'unique_together': {('proposal', 'voter')},
            },
        ),
    ]
