# Generated by Django 5.2.6 on 2025-12-14 00:11

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rb_core', '0038_collaboratorrole_can_invite_others_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='collaborativeproject',
            name='price_usd',
            field=models.DecimalField(decimal_places=2, default=Decimal('10.00'), help_text='NFT sale price in USD', max_digits=10),
        ),
    ]
