# Generated by Django 5.2.6 on 2025-12-14 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rb_core', '0039_add_price_to_collaborative_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='collaborativeproject',
            name='editions',
            field=models.PositiveIntegerField(default=1, help_text='Number of editions available for sale'),
        ),
        migrations.AddField(
            model_name='collaborativeproject',
            name='teaser_percent',
            field=models.PositiveIntegerField(default=10, help_text='Percentage of content shown as teaser (0-100)'),
        ),
        migrations.AddField(
            model_name='collaborativeproject',
            name='watermark_preview',
            field=models.BooleanField(default=False, help_text='Show watermark on teaser preview'),
        ),
    ]
