# Generated by Django 5.2.6 on 2025-12-14 05:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rb_core', '0040_add_editions_teaser_to_collaborative_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='collaborativeproject',
            name='published_content',
            field=models.ForeignKey(blank=True, help_text='Content record created when project is minted', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_collaborative_project', to='rb_core.content'),
        ),
    ]
