# Generated by Django 5.2.6 on 2025-12-16 21:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rb_core', '0041_add_published_content_to_collaborative_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='bio',
            field=models.TextField(blank=True, default='', max_length=2000),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='skills',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='social_links',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.CreateModel(
            name='ExternalPortfolioItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='', max_length=1000)),
                ('image', models.ImageField(blank=True, null=True, upload_to='portfolio/')),
                ('external_url', models.URLField(blank=True, default='')),
                ('project_type', models.CharField(choices=[('book', 'Book'), ('art', 'Art'), ('music', 'Music'), ('film', 'Film'), ('other', 'Other')], default='other', max_length=50)),
                ('role', models.CharField(blank=True, default='', max_length=100)),
                ('created_date', models.DateField(blank=True, null=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolio_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['order', '-created_at'],
                'indexes': [models.Index(fields=['user', 'order'], name='rb_core_ext_user_id_1f17a4_idx')],
            },
        ),
    ]
