# Generated by Django 5.2.6 on 2025-12-16 22:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rb_core', '0042_public_profile_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='collaboratorrole',
            name='cancellation_eligible',
            field=models.BooleanField(default=False, help_text='Whether owner can cancel due to breach'),
        ),
        migrations.AddField(
            model_name='collaboratorrole',
            name='contract_locked_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when contract was locked (on acceptance)', null=True),
        ),
        migrations.AddField(
            model_name='collaboratorrole',
            name='contract_version',
            field=models.PositiveIntegerField(default=1, help_text='Version of the contract, incremented on acceptance'),
        ),
        migrations.AddField(
            model_name='collaboratorrole',
            name='has_active_breach',
            field=models.BooleanField(default=False, help_text='Whether collaborator has an active deadline breach'),
        ),
        migrations.AddField(
            model_name='collaboratorrole',
            name='tasks_signed_off',
            field=models.PositiveIntegerField(default=0, help_text='Number of tasks signed off by owner'),
        ),
        migrations.AddField(
            model_name='collaboratorrole',
            name='tasks_total',
            field=models.PositiveIntegerField(default=0, help_text='Total number of contract tasks'),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='proposal_type',
            field=models.CharField(choices=[('revenue_split', 'Revenue Split Change'), ('new_member', 'Invite New Collaborator'), ('remove_member', 'Remove Collaborator'), ('project_change', 'Project Change'), ('deadline_extension', 'Deadline Extension'), ('exit_collaborator', 'Exit Collaborator'), ('contract_amendment', 'Contract Task Amendment')], max_length=30),
        ),
        migrations.CreateModel(
            name='ContractTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Brief title describing the deliverable', max_length=200)),
                ('description', models.TextField(blank=True, help_text="Detailed description of what's expected")),
                ('deadline', models.DateTimeField(help_text='Deadline for task completion')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('complete', 'Marked Complete'), ('signed_off', 'Signed Off'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('marked_complete_at', models.DateTimeField(blank=True, help_text='When collaborator marked task complete', null=True)),
                ('completion_notes', models.TextField(blank=True, help_text='Notes from collaborator when marking complete')),
                ('signed_off_at', models.DateTimeField(blank=True, help_text='When owner signed off on the task', null=True)),
                ('signoff_notes', models.TextField(blank=True, help_text='Notes from owner when signing off')),
                ('rejection_notes', models.TextField(blank=True, help_text='Reason for rejecting the completion')),
                ('rejected_at', models.DateTimeField(blank=True, help_text='When the completion was rejected', null=True)),
                ('is_overdue', models.BooleanField(default=False, help_text='Whether task has passed its deadline without sign-off')),
                ('overdue_notified_at', models.DateTimeField(blank=True, help_text='When overdue notification was sent', null=True)),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order of task in contract')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('collaborator_role', models.ForeignKey(help_text='The collaborator responsible for this task', on_delete=django.db.models.deletion.CASCADE, related_name='contract_tasks', to='rb_core.collaboratorrole')),
                ('marked_complete_by', models.ForeignKey(blank=True, help_text='User who marked the task complete', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks_marked_complete', to=settings.AUTH_USER_MODEL)),
                ('signed_off_by', models.ForeignKey(blank=True, help_text='Owner who signed off on the task', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks_signed_off', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['order', 'deadline'],
                'indexes': [models.Index(fields=['collaborator_role', 'status'], name='rb_core_con_collabo_fd18e4_idx'), models.Index(fields=['deadline', 'status'], name='rb_core_con_deadlin_59f4c4_idx'), models.Index(fields=['is_overdue'], name='rb_core_con_is_over_adfbab_idx')],
            },
        ),
    ]
