# Generated by Django 5.2.6 on 2025-12-18 07:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rb_core', '0043_contract_tasks'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoleDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('category', models.CharField(choices=[('creator', 'Creator'), ('contributor', 'Contributor'), ('reviewer', 'Reviewer'), ('technical', 'Technical'), ('management', 'Management')], max_length=20)),
                ('description', models.TextField()),
                ('applicable_to_book', models.BooleanField(default=False)),
                ('applicable_to_art', models.BooleanField(default=False)),
                ('applicable_to_music', models.BooleanField(default=False)),
                ('applicable_to_video', models.BooleanField(default=False)),
                ('default_permissions', models.JSONField(default=dict, help_text='Default permissions for this role')),
                ('ui_components', models.JSONField(default=list, help_text='List of UI components: chapter_editor, image_uploader, etc.')),
                ('icon', models.CharField(default='user', max_length=50)),
                ('color', models.CharField(default='#94a3b8', max_length=7)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['category', 'name'],
            },
        ),
        migrations.AddField(
            model_name='collaboratorrole',
            name='assigned_sections',
            field=models.ManyToManyField(blank=True, help_text='Specific sections this collaborator can edit', related_name='assigned_collaborators', to='rb_core.projectsection'),
        ),
        migrations.AddField(
            model_name='collaboratorrole',
            name='permissions',
            field=models.JSONField(blank=True, default=dict, help_text='Granular permissions for this collaborator'),
        ),
        migrations.AlterField(
            model_name='collaboratorrole',
            name='role',
            field=models.CharField(blank=True, help_text='Custom role name (or uses role_definition.name)', max_length=50),
        ),
        migrations.AddField(
            model_name='collaboratorrole',
            name='role_definition',
            field=models.ForeignKey(blank=True, help_text='Standard role template (if selected)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='collaborator_instances', to='rb_core.roledefinition'),
        ),
    ]
