# Generated by Django 5.2.6 on 2025-12-18 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rb_core', '0044_role_based_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='view_count',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
    ]
