# Generated by Django 5.2.6 on 2025-12-18 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rb_core', '0045_add_view_count_to_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookproject',
            name='cover_image',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to='book_covers/'),
        ),
    ]
