# Generated by Django 5.2.6 on 2025-12-19 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rb_core', '0046_increase_cover_image_max_length'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='content',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='status',
            field=models.CharField(choices=[('Available', 'Available'), ('Open to Offers', 'Open to Offers'), ('Selective', 'Selective'), ('Booked', 'Booked'), ('Unavailable', 'Unavailable'), ('On Hiatus', 'On Hiatus')], default='Available', max_length=32),
        ),
    ]
