# Generated by Django 5.2.6 on 2025-12-19 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rb_core', '0047_alter_content_options_alter_userprofile_status'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='purchase',
            index=models.Index(fields=['user', 'chapter'], name='rb_core_pur_user_id_fc5e41_idx'),
        ),
    ]
