# Generated by Django 5.2.6 on 2025-12-19 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rb_core', '0048_purchase_rb_core_pur_user_id_fc5e41_idx'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='purchase',
            index=models.Index(fields=['usdc_distribution_status'], name='rb_core_pur_usdc_di_7a9456_idx'),
        ),
    ]
