# Generated by Django 5.2.6 on 2025-12-19 23:39

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rb_core', '0049_purchase_rb_core_pur_usdc_di_7a9456_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='average_rating',
            field=models.DecimalField(blank=True, db_index=True, decimal_places=2, max_digits=3, null=True),
        ),
        migrations.AddField(
            model_name='content',
            name='like_count',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name='content',
            name='rating_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='average_review_rating',
            field=models.DecimalField(blank=True, db_index=True, decimal_places=2, max_digits=3, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='review_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('invitation', 'Collaboration Invitation'), ('invitation_response', 'Invitation Response'), ('counter_proposal', 'Counter Proposal'), ('comment', 'Comment'), ('approval', 'Approval Status Change'), ('section_update', 'Section Update'), ('revenue_proposal', 'Revenue Split Proposal'), ('mint_ready', 'Project Ready for Minting'), ('content_like', 'Content Like'), ('content_comment', 'Content Comment'), ('content_rating', 'Content Rating'), ('creator_review', 'Creator Review')], db_index=True, max_length=20),
        ),
        migrations.CreateModel(
            name='ContentComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=5000)),
                ('edited', models.BooleanField(default=False)),
                ('edit_history', models.JSONField(blank=True, default=list)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_comments', to=settings.AUTH_USER_MODEL)),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='rb_core.content')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_content_comments', to=settings.AUTH_USER_MODEL)),
                ('parent_comment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='rb_core.contentcomment')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['content', '-created_at'], name='rb_core_con_content_c3c133_idx'), models.Index(fields=['author', '-created_at'], name='rb_core_con_author__d4a42f_idx'), models.Index(fields=['parent_comment', '-created_at'], name='rb_core_con_parent__d1e255_idx'), models.Index(fields=['content', 'is_deleted', '-created_at'], name='rb_core_con_content_14c143_idx')],
            },
        ),
        migrations.CreateModel(
            name='ContentLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='rb_core.content')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_likes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['content', '-created_at'], name='rb_core_con_content_c3797f_idx'), models.Index(fields=['user', '-created_at'], name='rb_core_con_user_id_100b45_idx')],
                'unique_together': {('user', 'content')},
            },
        ),
        migrations.CreateModel(
            name='ContentRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(help_text='Star rating 1-5', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('review_text', models.TextField(blank=True, default='', max_length=2000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='rb_core.content')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_ratings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['content', '-created_at'], name='rb_core_con_content_89cad0_idx'), models.Index(fields=['content', 'rating'], name='rb_core_con_content_058b41_idx'), models.Index(fields=['user', '-created_at'], name='rb_core_con_user_id_6bd701_idx')],
                'unique_together': {('user', 'content')},
            },
        ),
        migrations.CreateModel(
            name='CreatorReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(help_text='Star rating 1-5', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('review_text', models.TextField(blank=True, default='', max_length=2000)),
                ('verification_type', models.CharField(choices=[('purchase', 'Verified Purchase'), ('collaboration', 'Past Collaborator')], max_length=20)),
                ('response_text', models.TextField(blank=True, default='', max_length=2000)),
                ('response_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creator_reviews', to=settings.AUTH_USER_MODEL)),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews_given', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['creator', '-created_at'], name='rb_core_cre_creator_e8aff9_idx'), models.Index(fields=['creator', 'rating'], name='rb_core_cre_creator_aba14c_idx'), models.Index(fields=['reviewer', '-created_at'], name='rb_core_cre_reviewe_f7ef2f_idx')],
                'unique_together': {('reviewer', 'creator')},
            },
        ),
    ]
