# Generated by Django 5.2.6 on 2025-12-20 21:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rb_core', '0054_follow_system'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(blank=True, max_length=40, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveConstraint(
            model_name='follow',
            name='unique_follow_relationship',
        ),
        migrations.RenameIndex(
            model_name='follow',
            new_name='rb_core_fol_followe_6d2354_idx',
            old_name='rb_core_fol_followe_idx',
        ),
        migrations.RenameIndex(
            model_name='follow',
            new_name='rb_core_fol_followi_8f2312_idx',
            old_name='rb_core_fol_followi_idx',
        ),
        migrations.AlterUniqueTogether(
            name='follow',
            unique_together={('follower', 'following')},
        ),
        migrations.AddField(
            model_name='contentview',
            name='content',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views', to='rb_core.content'),
        ),
        migrations.AddField(
            model_name='contentview',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='content_views', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='contentview',
            index=models.Index(fields=['content', 'user'], name='rb_core_con_content_a490d2_idx'),
        ),
        migrations.AddIndex(
            model_name='contentview',
            index=models.Index(fields=['content', 'session_key'], name='rb_core_con_content_a24cdb_idx'),
        ),
        migrations.AddIndex(
            model_name='contentview',
            index=models.Index(fields=['content', '-created_at'], name='rb_core_con_content_6ba758_idx'),
        ),
    ]
