# Generated by Django 5.2.6 on 2025-12-22 20:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rb_core', '0056_legal_agreement_tracking'),
    ]

    operations = [
        migrations.CreateModel(
            name='BatchPurchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_checkout_session_id', models.CharField(max_length=255, unique=True)),
                ('stripe_payment_intent_id', models.CharField(blank=True, default='', max_length=255)),
                ('total_items', models.PositiveIntegerField()),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('credit_card_fee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_charged', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('payment_pending', 'Payment Pending'), ('payment_completed', 'Payment Completed'), ('processing', 'Processing Mints'), ('completed', 'Completed'), ('partial', 'Partially Completed'), ('failed', 'Failed'), ('refunded', 'Fully Refunded')], default='payment_pending', max_length=20)),
                ('items_minted', models.PositiveIntegerField(default=0)),
                ('items_failed', models.PositiveIntegerField(default=0)),
                ('total_refunded', models.DecimalField(decimal_places=2, default=0, help_text='Total amount refunded for failed items', max_digits=10)),
                ('processing_log', models.JSONField(default=list, help_text='Log of minting attempts and results')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('checkout', 'In Checkout'), ('completed', 'Completed'), ('abandoned', 'Abandoned')], default='active', max_length=20)),
                ('stripe_checkout_session_id', models.CharField(blank=True, default='', max_length=255)),
                ('subtotal', models.DecimalField(blank=True, decimal_places=2, help_text='Sum of all item prices', max_digits=10, null=True)),
                ('credit_card_fee', models.DecimalField(blank=True, decimal_places=2, help_text='Single CC fee for entire cart', max_digits=10, null=True)),
                ('total', models.DecimalField(blank=True, decimal_places=2, help_text='Final amount charged to buyer', max_digits=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_price', models.DecimalField(decimal_places=2, help_text='Price when item was added to cart', max_digits=10)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['added_at'],
            },
        ),
        migrations.RenameIndex(
            model_name='legaldocument',
            new_name='rb_core_leg_documen_4332a8_idx',
            old_name='rb_core_leg_documen_a1b2c3_idx',
        ),
        migrations.RenameIndex(
            model_name='userlegalacceptance',
            new_name='rb_core_use_user_id_631a6e_idx',
            old_name='rb_core_use_user_id_d4e5f6_idx',
        ),
        migrations.RenameIndex(
            model_name='userlegalacceptance',
            new_name='rb_core_use_user_id_9035b0_idx',
            old_name='rb_core_use_user_id_g7h8i9_idx',
        ),
        migrations.AlterField(
            model_name='content',
            name='inventory_status',
            field=models.CharField(choices=[('draft', 'Draft'), ('minted', 'Minted'), ('unpublished', 'Unpublished')], default='draft', max_length=16),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='proposal_type',
            field=models.CharField(choices=[('revenue_split', 'Revenue Split Change'), ('new_member', 'Invite New Collaborator'), ('remove_member', 'Remove Collaborator'), ('project_change', 'Project Change'), ('deadline_extension', 'Deadline Extension'), ('exit_collaborator', 'Exit Collaborator'), ('contract_amendment', 'Contract Task Amendment'), ('unpublish_content', 'Unpublish Content')], max_length=30),
        ),
        migrations.AddField(
            model_name='batchpurchase',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batch_purchases', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='purchase',
            name='batch_purchase',
            field=models.ForeignKey(blank=True, help_text='Parent batch purchase if from cart checkout', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchases', to='rb_core.batchpurchase'),
        ),
        migrations.AddField(
            model_name='cart',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cart', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='cart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='rb_core.cart'),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='chapter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to='rb_core.chapter'),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='content',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to='rb_core.content'),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='creator',
            field=models.ForeignKey(help_text='Item creator for revenue distribution', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='batchpurchase',
            index=models.Index(fields=['user', 'status'], name='rb_core_bat_user_id_83f55c_idx'),
        ),
        migrations.AddIndex(
            model_name='batchpurchase',
            index=models.Index(fields=['status', '-created_at'], name='rb_core_bat_status_16c7fd_idx'),
        ),
        migrations.AddIndex(
            model_name='batchpurchase',
            index=models.Index(fields=['stripe_checkout_session_id'], name='rb_core_bat_stripe__571521_idx'),
        ),
        migrations.AddIndex(
            model_name='cart',
            index=models.Index(fields=['user', 'status'], name='rb_core_car_user_id_e6f767_idx'),
        ),
        migrations.AddIndex(
            model_name='cart',
            index=models.Index(fields=['status', '-updated_at'], name='rb_core_car_status_07a9b7_idx'),
        ),
        migrations.AddIndex(
            model_name='cartitem',
            index=models.Index(fields=['cart', 'chapter'], name='rb_core_car_cart_id_6fe72d_idx'),
        ),
        migrations.AddIndex(
            model_name='cartitem',
            index=models.Index(fields=['cart', 'content'], name='rb_core_car_cart_id_0634d7_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='cartitem',
            unique_together={('cart', 'chapter'), ('cart', 'content')},
        ),
    ]
