# Generated by Django 5.2.6 on 2025-12-23 20:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rb_core', '0057_batchpurchase_cart_cartitem_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookproject',
            name='series_order',
            field=models.PositiveIntegerField(default=0, help_text='Order of this book within the series'),
        ),
        migrations.AddField(
            model_name='chapter',
            name='synopsis',
            field=models.TextField(blank=True, default='', help_text='Brief summary of this chapter (max ~150 words)'),
        ),
        migrations.AddField(
            model_name='projectsection',
            name='synopsis',
            field=models.TextField(blank=True, default='', help_text='Brief summary of this section (max ~150 words)'),
        ),
        migrations.AlterField(
            model_name='bookproject',
            name='description',
            field=models.TextField(blank=True, default='', help_text='Book synopsis (max ~200 words)'),
        ),
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('synopsis', models.TextField(blank=True, default='', help_text='Overview of the series (max ~300 words)')),
                ('cover_image', models.ImageField(blank=True, max_length=500, null=True, upload_to='series_covers/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_series', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Series',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.AddField(
            model_name='bookproject',
            name='series',
            field=models.ForeignKey(blank=True, help_text='Optional series this book belongs to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='books', to='rb_core.series'),
        ),
    ]
