# Generated by Django 5.2.6 on 2025-12-30 05:24

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rb_core', '0058_bookproject_series_order_chapter_synopsis_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='bridge_payout_percentage',
            field=models.PositiveSmallIntegerField(default=100, help_text="Percentage sent to Bridge (rest goes to wallet). Only used when payout_destination='split'", validators=[django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='payout_destination',
            field=models.CharField(choices=[('wallet', 'Web3 Wallet'), ('bridge', 'Bank Account (via Bridge)'), ('split', 'Split (Wallet + Bank)')], default='wallet', help_text='Where to send USDC earnings', max_length=32),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='pending_bridge_amount',
            field=models.DecimalField(decimal_places=6, default=Decimal('0'), help_text='Accumulated USDC awaiting Bridge payout threshold ($10)', max_digits=18),
        ),
        migrations.CreateModel(
            name='BridgeCustomer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bridge_customer_id', models.CharField(help_text="Bridge's customer ID", max_length=128, unique=True)),
                ('kyc_status', models.CharField(choices=[('not_started', 'Not Started'), ('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('incomplete', 'Incomplete')], default='not_started', max_length=32)),
                ('kyc_link', models.URLField(blank=True, help_text='KYC verification URL from Bridge')),
                ('kyc_completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bridge_customer', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Bridge Customer',
                'verbose_name_plural': 'Bridge Customers',
            },
        ),
        migrations.CreateModel(
            name='BridgeExternalAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bridge_external_account_id', models.CharField(max_length=128, unique=True)),
                ('account_name', models.CharField(help_text="e.g., 'Chase ****1234'", max_length=255)),
                ('bank_name', models.CharField(blank=True, max_length=255)),
                ('last_four', models.CharField(blank=True, max_length=4)),
                ('account_type', models.CharField(blank=True, choices=[('checking', 'Checking'), ('savings', 'Savings')], max_length=32)),
                ('is_active', models.BooleanField(default=True)),
                ('is_default', models.BooleanField(default=False, help_text='Default account for new liquidation addresses')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bridge_customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='external_accounts', to='rb_core.bridgecustomer')),
            ],
            options={
                'ordering': ['-is_default', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BridgeLiquidationAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bridge_liquidation_address_id', models.CharField(max_length=128, unique=True)),
                ('solana_address', models.CharField(help_text='Solana address for USDC deposits', max_length=44, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_primary', models.BooleanField(default=False, help_text='Primary address for receiving payouts')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bridge_customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liquidation_addresses', to='rb_core.bridgecustomer')),
                ('external_account', models.ForeignKey(help_text='Bank account to receive converted funds', on_delete=django.db.models.deletion.PROTECT, related_name='liquidation_addresses', to='rb_core.bridgeexternalaccount')),
            ],
            options={
                'ordering': ['-is_primary', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BridgeDrain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bridge_drain_id', models.CharField(max_length=128, unique=True)),
                ('usdc_amount', models.DecimalField(decimal_places=6, help_text='USDC received', max_digits=18)),
                ('usd_amount', models.DecimalField(decimal_places=2, help_text='USD deposited after conversion', max_digits=18)),
                ('fee_amount', models.DecimalField(decimal_places=2, default=0, help_text='Bridge conversion fee', max_digits=18)),
                ('source_tx_signature', models.CharField(blank=True, help_text='Solana tx that funded this drain', max_length=128)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=32)),
                ('initiated_at', models.DateTimeField(help_text='When Bridge detected the incoming USDC')),
                ('completed_at', models.DateTimeField(blank=True, help_text='When USD was deposited to bank', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('liquidation_address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drains', to='rb_core.bridgeliquidationaddress')),
            ],
            options={
                'ordering': ['-initiated_at'],
            },
        ),
        migrations.AddIndex(
            model_name='bridgecustomer',
            index=models.Index(fields=['kyc_status'], name='rb_core_bri_kyc_sta_e6f420_idx'),
        ),
        migrations.AddIndex(
            model_name='bridgeexternalaccount',
            index=models.Index(fields=['bridge_customer', 'is_active'], name='rb_core_bri_bridge__bd8add_idx'),
        ),
        migrations.AddIndex(
            model_name='bridgeliquidationaddress',
            index=models.Index(fields=['bridge_customer', 'is_active'], name='rb_core_bri_bridge__1f8bee_idx'),
        ),
        migrations.AddIndex(
            model_name='bridgeliquidationaddress',
            index=models.Index(fields=['solana_address'], name='rb_core_bri_solana__52207e_idx'),
        ),
        migrations.AddIndex(
            model_name='bridgedrain',
            index=models.Index(fields=['liquidation_address', 'status'], name='rb_core_bri_liquida_0aa251_idx'),
        ),
        migrations.AddIndex(
            model_name='bridgedrain',
            index=models.Index(fields=['status', '-initiated_at'], name='rb_core_bri_status_37a73f_idx'),
        ),
        migrations.AddIndex(
            model_name='bridgedrain',
            index=models.Index(fields=['source_tx_signature'], name='rb_core_bri_source__51c1a7_idx'),
        ),
    ]
