# Generated by Django 5.2.6 on 2025-12-30 06:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rb_core', '0059_add_bridge_models'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batchpurchase',
            name='status',
            field=models.CharField(choices=[('payment_pending', 'Payment Pending'), ('payment_completed', 'Payment Completed'), ('bridge_pending', 'Awaiting Bridge Conversion'), ('bridge_converting', 'Converting USD to USDC'), ('usdc_received', 'USDC Received'), ('processing', 'Processing Mints'), ('completed', 'Completed'), ('partial', 'Partially Completed'), ('failed', 'Failed'), ('refunded', 'Fully Refunded')], default='payment_pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='status',
            field=models.CharField(choices=[('payment_pending', 'Payment Pending'), ('payment_completed', 'Payment Completed'), ('bridge_pending', 'Awaiting Bridge Conversion'), ('bridge_converting', 'Converting USD to USDC'), ('usdc_received', 'USDC Received'), ('minting', 'Minting NFT'), ('completed', 'Completed'), ('failed', 'Failed'), ('refunded', 'Refunded')], default='payment_pending', max_length=20),
        ),
        migrations.CreateModel(
            name='BridgeOnRampTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bridge_transfer_id', models.CharField(help_text="Bridge's transfer ID from Transfers API", max_length=128, unique=True)),
                ('bridge_source_deposit_id', models.CharField(blank=True, help_text="Bridge's source deposit ID (if using virtual accounts)", max_length=128)),
                ('stripe_payment_intent_id', models.CharField(db_index=True, help_text='Stripe payment intent ID that funded this transfer', max_length=255)),
                ('usd_amount', models.DecimalField(decimal_places=2, help_text='USD amount sent to Bridge (after Stripe fees)', max_digits=10)),
                ('usdc_amount', models.DecimalField(blank=True, decimal_places=6, help_text='USDC received from Bridge (may differ due to Bridge fees)', max_digits=10, null=True)),
                ('bridge_fee', models.DecimalField(decimal_places=2, default=0, help_text="Bridge's conversion fee", max_digits=10)),
                ('destination_wallet', models.CharField(help_text="Platform's Solana wallet address where USDC is delivered", max_length=44)),
                ('status', models.CharField(choices=[('pending', 'Pending - Transfer Created'), ('awaiting_funds', 'Awaiting Funds from Stripe'), ('funds_received', 'Funds Received by Bridge'), ('converting', 'Converting USD to USDC'), ('completed', 'Completed - USDC Delivered'), ('failed', 'Failed'), ('refunded', 'Refunded via Stripe')], default='pending', max_length=32)),
                ('failure_reason', models.TextField(blank=True, help_text="Reason for failure if status is 'failed'")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('funds_received_at', models.DateTimeField(blank=True, help_text='When Bridge received USD funds', null=True)),
                ('conversion_completed_at', models.DateTimeField(blank=True, help_text='When Bridge delivered USDC to platform wallet', null=True)),
                ('solana_tx_signature', models.CharField(blank=True, help_text='Solana transaction where Bridge delivered USDC', max_length=128)),
                ('batch_purchase', models.OneToOneField(blank=True, help_text='Batch purchase this on-ramp is for', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bridge_onramp', to='rb_core.batchpurchase')),
                ('purchase', models.OneToOneField(blank=True, help_text='Single purchase this on-ramp is for', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bridge_onramp', to='rb_core.purchase')),
            ],
            options={
                'verbose_name': 'Bridge On-Ramp Transfer',
                'verbose_name_plural': 'Bridge On-Ramp Transfers',
                'indexes': [models.Index(fields=['status'], name='rb_core_bri_status_f0f595_idx'), models.Index(fields=['bridge_transfer_id'], name='rb_core_bri_bridge__2d7c2a_idx'), models.Index(fields=['stripe_payment_intent_id'], name='rb_core_bri_stripe__73e6a0_idx'), models.Index(fields=['status', '-created_at'], name='rb_core_bri_status_dc973a_idx')],
            },
        ),
    ]
