# Generated by Django 5.2.6 on 2025-12-30 06:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rb_core', '0060_bridge_onramp'),
    ]

    operations = [
        migrations.AddField(
            model_name='roledefinition',
            name='applicable_to_comic',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='collaborativeproject',
            name='content_type',
            field=models.CharField(choices=[('book', 'Book'), ('music', 'Music'), ('video', 'Video'), ('art', 'Art'), ('comic', 'Comic')], max_length=16),
        ),
        migrations.CreateModel(
            name='ComicPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_number', models.PositiveIntegerField()),
                ('page_format', models.CharField(choices=[('standard', 'Standard (Letter 8.5x11)'), ('manga', 'Manga (B5)'), ('webtoon', 'Webtoon (Vertical Scroll)'), ('custom', 'Custom')], default='standard', max_length=20)),
                ('canvas_width', models.PositiveIntegerField(default=2550)),
                ('canvas_height', models.PositiveIntegerField(default=3300)),
                ('background_image', models.FileField(blank=True, null=True, upload_to='comic_pages/')),
                ('background_color', models.CharField(default='#FFFFFF', max_length=7)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comic_pages', to='rb_core.collaborativeproject')),
            ],
            options={
                'ordering': ['page_number'],
                'unique_together': {('project', 'page_number')},
            },
        ),
        migrations.CreateModel(
            name='ComicPanel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('y_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('width_percent', models.DecimalField(decimal_places=2, default=50, max_digits=5)),
                ('height_percent', models.DecimalField(decimal_places=2, default=50, max_digits=5)),
                ('z_index', models.IntegerField(default=0)),
                ('border_style', models.CharField(choices=[('solid', 'Solid'), ('dashed', 'Dashed'), ('none', 'None'), ('jagged', 'Jagged/Action'), ('wavy', 'Wavy')], default='solid', max_length=20)),
                ('border_width', models.PositiveIntegerField(default=2)),
                ('border_color', models.CharField(default='#000000', max_length=7)),
                ('border_radius', models.PositiveIntegerField(default=0)),
                ('background_color', models.CharField(default='#FFFFFF', max_length=7)),
                ('rotation', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('artwork', models.FileField(blank=True, help_text='Panel artwork uploaded by artist', null=True, upload_to='comic_panels/')),
                ('artwork_fit', models.CharField(choices=[('contain', 'Contain'), ('cover', 'Cover'), ('fill', 'Fill')], default='cover', max_length=20)),
                ('order', models.PositiveIntegerField(default=0, help_text='Reading order within page')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('artist', models.ForeignKey(blank=True, help_text="Artist responsible for this panel's artwork", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_panels', to=settings.AUTH_USER_MODEL)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='panels', to='rb_core.comicpage')),
            ],
            options={
                'ordering': ['page', 'order', 'z_index'],
            },
        ),
        migrations.CreateModel(
            name='SpeechBubble',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bubble_type', models.CharField(choices=[('oval', 'Standard Oval'), ('thought', 'Thought Cloud'), ('shout', 'Shout/Jagged'), ('whisper', 'Whisper (dotted)'), ('narrative', 'Narrative Box'), ('caption', 'Caption'), ('radio', 'Radio/Electronic'), ('burst', 'Action Burst')], default='oval', max_length=20)),
                ('x_percent', models.DecimalField(decimal_places=2, default=50, max_digits=5)),
                ('y_percent', models.DecimalField(decimal_places=2, default=50, max_digits=5)),
                ('width_percent', models.DecimalField(decimal_places=2, default=30, max_digits=5)),
                ('height_percent', models.DecimalField(decimal_places=2, default=20, max_digits=5)),
                ('z_index', models.IntegerField(default=10)),
                ('text', models.TextField(blank=True)),
                ('font_family', models.CharField(default='Comic Sans MS', max_length=100)),
                ('font_size', models.PositiveIntegerField(default=14)),
                ('font_color', models.CharField(default='#000000', max_length=7)),
                ('font_weight', models.CharField(choices=[('normal', 'Normal'), ('bold', 'Bold')], default='normal', max_length=10)),
                ('font_style', models.CharField(choices=[('normal', 'Normal'), ('italic', 'Italic')], default='normal', max_length=10)),
                ('text_align', models.CharField(choices=[('left', 'Left'), ('center', 'Center'), ('right', 'Right')], default='center', max_length=10)),
                ('background_color', models.CharField(default='#FFFFFF', max_length=7)),
                ('border_color', models.CharField(default='#000000', max_length=7)),
                ('border_width', models.PositiveIntegerField(default=2)),
                ('pointer_direction', models.CharField(choices=[('none', 'None'), ('top', 'Top'), ('bottom', 'Bottom'), ('left', 'Left'), ('right', 'Right'), ('top-left', 'Top Left'), ('top-right', 'Top Right'), ('bottom-left', 'Bottom Left'), ('bottom-right', 'Bottom Right')], default='bottom', max_length=20)),
                ('pointer_position', models.DecimalField(decimal_places=2, default=50, max_digits=5)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('panel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='speech_bubbles', to='rb_core.comicpanel')),
                ('writer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='written_bubbles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['panel', 'order', 'z_index'],
            },
        ),
    ]
