# Generated by Django 5.2.6 on 2025-12-30 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rb_core', '0061_add_comic_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='comicpanel',
            name='skew_x',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='comicpanel',
            name='skew_y',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='comicpanel',
            name='artwork',
            field=models.FileField(blank=True, help_text='Panel artwork uploaded by artist', max_length=500, null=True, upload_to='comic_panels/'),
        ),
    ]
