# Generated by Django 5.2.6 on 2025-12-30 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rb_core', '0062_add_panel_skew_and_artwork_maxlength'),
    ]

    operations = [
        migrations.AddField(
            model_name='collaborativeproject',
            name='is_solo',
            field=models.BooleanField(default=False, help_text='True if this is a solo project (single creator, no collaborators)'),
        ),
    ]
