# Generated by Django 5.2.6 on 2025-12-30 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rb_core', '0063_collaborativeproject_is_solo'),
    ]

    operations = [
        migrations.AddField(
            model_name='collaborativeproject',
            name='cover_image',
            field=models.ImageField(blank=True, help_text='Cover image for the project', max_length=500, null=True, upload_to='project_covers/'),
        ),
    ]
