# Generated by Django 5.2.6 on 2025-12-30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rb_core', '0064_collaborativeproject_cover_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # Create ComicSeries model
        migrations.CreateModel(
            name='ComicSeries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('synopsis', models.TextField(blank=True, default='', help_text='Series description')),
                ('cover_image', models.ImageField(blank=True, max_length=500, null=True, upload_to='comic_series_covers/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_published', models.BooleanField(default=False)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comic_series', to=settings.AUTH_USER_MODEL)),
                ('published_content', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_comic_series', to='rb_core.content')),
            ],
            options={
                'verbose_name_plural': 'Comic Series',
                'ordering': ['-updated_at'],
            },
        ),
        # Create ComicIssue model
        migrations.CreateModel(
            name='ComicIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('issue_number', models.PositiveIntegerField(default=1)),
                ('synopsis', models.TextField(blank=True, default='', help_text='Issue synopsis')),
                ('cover_image', models.ImageField(blank=True, max_length=500, null=True, upload_to='comic_issue_covers/')),
                ('price', models.DecimalField(decimal_places=2, default=1.0, help_text='Price in USD for this issue', max_digits=10)),
                ('is_published', models.BooleanField(default=False)),
                ('is_listed', models.BooleanField(db_index=True, default=True, help_text='Whether this issue is visible in the marketplace')),
                ('delisted_at', models.DateTimeField(blank=True, null=True)),
                ('delisted_reason', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('series', models.ForeignKey(blank=True, help_text='Optional series this issue belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='rb_core.comicseries')),
                ('project', models.ForeignKey(blank=True, help_text='Collaborative project for this issue', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comic_issues', to='rb_core.collaborativeproject')),
                ('published_content', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_comic_issue', to='rb_core.content')),
                ('delisted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delisted_comic_issues', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['issue_number', 'created_at'],
            },
        ),
        # Add issue FK to ComicPage (nullable for migration)
        migrations.AddField(
            model_name='comicpage',
            name='issue',
            field=models.ForeignKey(blank=True, help_text='Issue this page belongs to (for chapter-based publishing)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='issue_pages', to='rb_core.comicissue'),
        ),
        # Make project FK nullable on ComicPage
        migrations.AlterField(
            model_name='comicpage',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comic_pages', to='rb_core.collaborativeproject'),
        ),
        # Remove old unique_together constraint
        migrations.AlterUniqueTogether(
            name='comicpage',
            unique_together=set(),
        ),
        # Add new constraints
        migrations.AddConstraint(
            model_name='comicpage',
            constraint=models.UniqueConstraint(condition=models.Q(('issue__isnull', False)), fields=('issue', 'page_number'), name='unique_issue_page_number'),
        ),
        migrations.AddConstraint(
            model_name='comicpage',
            constraint=models.UniqueConstraint(condition=models.Q(('project__isnull', False)), fields=('project', 'page_number'), name='unique_project_page_number'),
        ),
    ]
