# Generated by Django 5.2.6 on 2025-12-30
# Data migration to convert existing comics to use the issue system

from django.db import migrations


def migrate_comics_to_issues(apps, schema_editor):
    """
    For each comic CollaborativeProject, create a ComicIssue #1 and move pages to it.
    This preserves existing comics while enabling the new chapter/issue system.
    """
    CollaborativeProject = apps.get_model('rb_core', 'CollaborativeProject')
    ComicIssue = apps.get_model('rb_core', 'ComicIssue')
    ComicPage = apps.get_model('rb_core', 'ComicPage')

    # Find all comic projects
    comic_projects = CollaborativeProject.objects.filter(content_type='comic')

    for project in comic_projects:
        # Check if this project already has issues (skip if migrated)
        if project.comic_issues.exists():
            continue

        # Create Issue #1 for this project
        issue = ComicIssue.objects.create(
            project=project,
            title=project.title or 'Issue #1',
            issue_number=1,
            synopsis=project.description or '',
            is_published=(project.status == 'minted'),
            published_content=project.published_content,
            price=1.00,  # Default price
        )

        # Move all pages from project to issue
        pages = ComicPage.objects.filter(project=project)
        pages.update(issue=issue)

        print(f"Migrated {pages.count()} pages from '{project.title}' to Issue #1")


def reverse_migration(apps, schema_editor):
    """
    Reverse the migration by removing issue FKs from pages.
    Note: This doesn't delete the ComicIssue records.
    """
    ComicPage = apps.get_model('rb_core', 'ComicPage')
    # Clear issue FK from all pages (they still have project FK)
    ComicPage.objects.all().update(issue=None)


class Migration(migrations.Migration):

    dependencies = [
        ('rb_core', '0065_add_comic_series_and_issue'),
    ]

    operations = [
        migrations.RunPython(migrate_comics_to_issues, reverse_migration),
    ]
