# Generated by Django 5.2.6 on 2025-12-30 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rb_core', '0066_migrate_comics_to_issues'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='content_type',
            field=models.CharField(choices=[('book', 'Book'), ('art', 'Art'), ('film', 'Film'), ('music', 'Music'), ('comic', 'Comic')], default='book', max_length=16),
        ),
    ]
