# Generated by Django 5.2.6 on 2025-12-31 05:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rb_core', '0067_alter_content_content_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='comicpage',
            name='default_gutter_width',
            field=models.DecimalField(decimal_places=2, default=2.0, help_text='Default gutter/line width in percentage of page width', max_digits=5),
        ),
        migrations.AddField(
            model_name='comicpage',
            name='default_line_color',
            field=models.CharField(default='#000000', help_text='Default color for divider lines', max_length=7),
        ),
        migrations.AddField(
            model_name='comicpage',
            name='gutter_mode',
            field=models.BooleanField(default=True, help_text='True = visible gutters between panels, False = border lines only'),
        ),
        migrations.AddField(
            model_name='comicpage',
            name='layout_version',
            field=models.IntegerField(default=2, help_text='1 = legacy rectangle-based panels, 2 = line-based dividers'),
        ),
        migrations.AddField(
            model_name='comicpage',
            name='orientation',
            field=models.CharField(choices=[('portrait', 'Portrait (8.5x11)'), ('landscape', 'Landscape (11x8.5)'), ('square', 'Square (10x10)'), ('webtoon', 'Webtoon (Vertical Scroll)'), ('manga_b5', 'Manga B5'), ('social_square', 'Social Square (1:1)'), ('social_story', 'Social Story (9:16)')], default='portrait', help_text='Page orientation/aspect ratio preset', max_length=20),
        ),
        migrations.CreateModel(
            name='DividerLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_type', models.CharField(choices=[('straight', 'Straight'), ('bezier', 'Bezier Curve')], default='straight', max_length=20)),
                ('start_x', models.DecimalField(decimal_places=3, max_digits=6)),
                ('start_y', models.DecimalField(decimal_places=3, max_digits=6)),
                ('end_x', models.DecimalField(decimal_places=3, max_digits=6)),
                ('end_y', models.DecimalField(decimal_places=3, max_digits=6)),
                ('control1_x', models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True)),
                ('control1_y', models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True)),
                ('control2_x', models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True)),
                ('control2_y', models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True)),
                ('thickness', models.DecimalField(blank=True, decimal_places=2, help_text='Line thickness in percentage of page width. Overrides page default if set.', max_digits=5, null=True)),
                ('color', models.CharField(blank=True, help_text='Line color in hex. Overrides page default if set.', max_length=7, null=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='divider_lines', to='rb_core.comicpage')),
            ],
            options={
                'ordering': ['page', 'order'],
            },
        ),
    ]
