# Generated by Django 5.2.6 on 2025-12-31 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rb_core', '0068_comicpage_default_gutter_width_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dividerline',
            name='control1_x',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='dividerline',
            name='control1_y',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='dividerline',
            name='control2_x',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='dividerline',
            name='control2_y',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='dividerline',
            name='end_x',
            field=models.DecimalField(decimal_places=4, max_digits=10),
        ),
        migrations.AlterField(
            model_name='dividerline',
            name='end_y',
            field=models.DecimalField(decimal_places=4, max_digits=10),
        ),
        migrations.AlterField(
            model_name='dividerline',
            name='start_x',
            field=models.DecimalField(decimal_places=4, max_digits=10),
        ),
        migrations.AlterField(
            model_name='dividerline',
            name='start_y',
            field=models.DecimalField(decimal_places=4, max_digits=10),
        ),
    ]
