# Generated by Django 5.2.6 on 2026-01-02 23:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rb_core', '0069_update_dividerline_decimal_precision'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comicpage',
            name='default_line_color',
            field=models.CharField(default='#6b7280', help_text='Default color for divider lines', max_length=7),
        ),
        migrations.CreateModel(
            name='ArtworkLibraryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(help_text='Original artwork file', max_length=500, upload_to='artwork_library/')),
                ('thumbnail', models.FileField(blank=True, help_text='Thumbnail for sidebar display', max_length=500, null=True, upload_to='artwork_library/thumbnails/')),
                ('title', models.CharField(blank=True, help_text='Display name', max_length=200)),
                ('filename', models.CharField(help_text='Original filename', max_length=255)),
                ('width', models.PositiveIntegerField(default=0, help_text='Image width in pixels')),
                ('height', models.PositiveIntegerField(default=0, help_text='Image height in pixels')),
                ('file_size', models.PositiveIntegerField(default=0, help_text='File size in bytes')),
                ('usage_count', models.PositiveIntegerField(default=0, help_text='Times used in panels')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(help_text='Parent comic project', on_delete=django.db.models.deletion.CASCADE, related_name='artwork_library', to='rb_core.collaborativeproject')),
                ('uploader', models.ForeignKey(help_text='User who uploaded this artwork', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_artwork', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Artwork Library Item',
                'verbose_name_plural': 'Artwork Library Items',
                'ordering': ['-created_at'],
            },
        ),
    ]
