# Generated by Django 5.2.6 on 2026-01-08 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rb_core', '0070_add_artwork_library'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='copyright_holder',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='content',
            name='copyright_year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
