# Generated by Django 5.2.6 on 2026-01-08 06:12

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rb_core', '0071_add_copyright_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='payment_provider',
            field=models.CharField(choices=[('stripe', 'Stripe'), ('circle', 'Circle'), ('balance', 'Balance (USDC)'), ('coinbase', 'Coinbase Onramp'), ('direct_crypto', 'Direct Crypto')], default='stripe', help_text='Payment provider used for this purchase', max_length=20),
        ),
        migrations.CreateModel(
            name='PurchaseIntent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_cart_purchase', models.BooleanField(default=False)),
                ('cart_snapshot', models.JSONField(blank=True, help_text='Snapshot of cart items at time of intent', null=True)),
                ('item_price', models.DecimalField(decimal_places=2, help_text='Price of item(s) at time of intent', max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, help_text='Total amount including any fees', max_digits=10)),
                ('payment_method', models.CharField(blank=True, choices=[('balance', 'Pay with Balance'), ('coinbase', 'Coinbase Onramp'), ('direct_crypto', 'Direct Crypto'), ('stripe', 'Stripe (Legacy)')], max_length=20)),
                ('status', models.CharField(choices=[('created', 'Created'), ('payment_method_selected', 'Payment Method Selected'), ('awaiting_payment', 'Awaiting Payment'), ('payment_received', 'Payment Received'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('expired', 'Expired'), ('canceled', 'Canceled')], default='created', max_length=30)),
                ('user_balance_at_creation', models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True)),
                ('balance_sufficient', models.BooleanField(default=False)),
                ('coinbase_minimum_add', models.DecimalField(blank=True, decimal_places=2, help_text='Minimum amount user must add via Coinbase ($5 min)', max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expires_at', models.DateTimeField()),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('failure_reason', models.TextField(blank=True)),
                ('batch_purchase', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_intent', to='rb_core.batchpurchase')),
                ('chapter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='purchase_intents', to='rb_core.chapter')),
                ('content', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='purchase_intents', to='rb_core.content')),
                ('purchase', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_intent', to='rb_core.purchase')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_intents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DirectCryptoTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expected_amount', models.DecimalField(decimal_places=6, help_text='Expected USDC amount', max_digits=18)),
                ('received_amount', models.DecimalField(blank=True, decimal_places=6, help_text='Actual USDC received', max_digits=18, null=True)),
                ('payment_memo', models.CharField(help_text='Unique memo to identify this payment (e.g., RB-ABC123)', max_length=64, unique=True)),
                ('from_wallet', models.CharField(blank=True, help_text='Source wallet address (detected from transaction)', max_length=44)),
                ('to_wallet', models.CharField(help_text='Platform USDC receiving address', max_length=44)),
                ('solana_tx_signature', models.CharField(blank=True, help_text='Solana transaction signature', max_length=128)),
                ('status', models.CharField(choices=[('awaiting_payment', 'Awaiting Payment'), ('detected', 'Payment Detected'), ('confirming', 'Confirming'), ('confirmed', 'Confirmed'), ('processing', 'Processing Purchase'), ('completed', 'Completed'), ('expired', 'Expired'), ('failed', 'Failed')], default='awaiting_payment', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expires_at', models.DateTimeField(help_text='Payment must arrive before this time')),
                ('detected_at', models.DateTimeField(blank=True, null=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('failure_reason', models.TextField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='direct_crypto_transactions', to=settings.AUTH_USER_MODEL)),
                ('purchase_intent', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='direct_crypto_transaction', to='rb_core.purchaseintent')),
            ],
            options={
                'verbose_name': 'Direct Crypto Transaction',
                'verbose_name_plural': 'Direct Crypto Transactions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CoinbaseTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coinbase_charge_id', models.CharField(help_text='Coinbase Commerce charge ID or Onramp session ID', max_length=128, unique=True)),
                ('coinbase_checkout_id', models.CharField(blank=True, help_text='Coinbase checkout session ID', max_length=128)),
                ('fiat_amount', models.DecimalField(decimal_places=2, help_text='Amount in USD charged to user', max_digits=10)),
                ('usdc_amount', models.DecimalField(blank=True, decimal_places=6, help_text='USDC received (after fees)', max_digits=18, null=True)),
                ('coinbase_fee', models.DecimalField(blank=True, decimal_places=2, help_text='Coinbase processing fee', max_digits=10, null=True)),
                ('destination_wallet', models.CharField(help_text="User's Web3Auth Solana wallet address", max_length=44)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('expired', 'Expired'), ('canceled', 'Canceled')], default='pending', max_length=20)),
                ('solana_tx_signature', models.CharField(blank=True, help_text='Solana transaction signature for USDC deposit', max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('failure_reason', models.TextField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coinbase_transactions', to=settings.AUTH_USER_MODEL)),
                ('purchase_intent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coinbase_transactions', to='rb_core.purchaseintent')),
            ],
            options={
                'verbose_name': 'Coinbase Transaction',
                'verbose_name_plural': 'Coinbase Transactions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usdc_balance', models.DecimalField(decimal_places=6, default=Decimal('0'), help_text='Cached USDC balance from blockchain', max_digits=18)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('sync_status', models.CharField(choices=[('synced', 'Synced'), ('syncing', 'Syncing'), ('stale', 'Stale'), ('error', 'Error')], default='stale', max_length=20)),
                ('last_slot', models.BigIntegerField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='usdc_balance', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Balance',
                'verbose_name_plural': 'User Balances',
            },
        ),
        migrations.AddIndex(
            model_name='purchaseintent',
            index=models.Index(fields=['user', 'status', '-created_at'], name='rb_core_pur_user_id_a21961_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaseintent',
            index=models.Index(fields=['status', 'expires_at'], name='rb_core_pur_status_113d76_idx'),
        ),
        migrations.AddIndex(
            model_name='directcryptotransaction',
            index=models.Index(fields=['status', 'expires_at'], name='rb_core_dir_status_83eed1_idx'),
        ),
        migrations.AddIndex(
            model_name='directcryptotransaction',
            index=models.Index(fields=['payment_memo'], name='rb_core_dir_payment_28a35c_idx'),
        ),
        migrations.AddIndex(
            model_name='directcryptotransaction',
            index=models.Index(fields=['to_wallet', 'status'], name='rb_core_dir_to_wall_5eb5eb_idx'),
        ),
        migrations.AddIndex(
            model_name='coinbasetransaction',
            index=models.Index(fields=['user', '-created_at'], name='rb_core_coi_user_id_e1093f_idx'),
        ),
        migrations.AddIndex(
            model_name='coinbasetransaction',
            index=models.Index(fields=['status', '-created_at'], name='rb_core_coi_status_42de49_idx'),
        ),
        migrations.AddIndex(
            model_name='coinbasetransaction',
            index=models.Index(fields=['coinbase_charge_id'], name='rb_core_coi_coinbas_949c1d_idx'),
        ),
    ]
