# Generated by Django 5.2.6 on 2026-01-09 21:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rb_core', '0072_add_dual_payment_models'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='bookproject',
            unique_together={('creator', 'title')},
        ),
        migrations.AlterUniqueTogether(
            name='collaborativeproject',
            unique_together={('created_by', 'title')},
        ),
        migrations.AlterUniqueTogether(
            name='comicseries',
            unique_together={('creator', 'title')},
        ),
    ]
