# Generated by Django 5.2.6 on 2026-01-12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rb_core', '0073_unique_titles'),
    ]

    operations = [
        migrations.AddField(
            model_name='speechbubble',
            name='tail_end_x_percent',
            field=models.DecimalField(
                decimal_places=2,
                default=50,
                help_text='X position where tail tip points (as % of panel width)',
                max_digits=6,
            ),
        ),
        migrations.AddField(
            model_name='speechbubble',
            name='tail_end_y_percent',
            field=models.DecimalField(
                decimal_places=2,
                default=120,
                help_text='Y position where tail tip points (as % of panel height). >100 means below panel.',
                max_digits=6,
            ),
        ),
        migrations.AddField(
            model_name='speechbubble',
            name='tail_type',
            field=models.CharField(
                choices=[
                    ('straight', 'Straight'),
                    ('curved', 'Curved'),
                    ('dots', 'Thought Dots'),
                ],
                default='curved',
                help_text='Style of the tail: straight, curved bezier, or dots for thought bubbles',
                max_length=20,
            ),
        ),
    ]
