# Generated by Django 5.2.6 on 2026-01-12 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rb_core', '0074_speech_bubble_tail_system'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comicpage',
            name='default_gutter_width',
            field=models.DecimalField(decimal_places=2, default=0.5, help_text='Default gutter/line width in percentage of page width', max_digits=5),
        ),
    ]
