# Generated by Django 5.2.6 on 2026-01-12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rb_core', '0075_alter_comicpage_default_gutter_width'),
    ]

    operations = [
        # Add new bubble style preset field
        migrations.AddField(
            model_name='speechbubble',
            name='bubble_style',
            field=models.CharField(
                choices=[
                    ('manga', 'Manga/Japanese'),
                    ('western', 'Western/American'),
                    ('custom', 'Custom'),
                ],
                default='manga',
                help_text='Overall style preset: manga (clean, thin strokes) or western (halftone, thick strokes)',
                max_length=20,
            ),
        ),
        # Add speed lines toggle for manga emphasis
        migrations.AddField(
            model_name='speechbubble',
            name='speed_lines_enabled',
            field=models.BooleanField(
                default=False,
                help_text='Enable radial speed lines (manga-style emphasis effect)',
            ),
        ),
        # Add halftone shadow for western comics style
        migrations.AddField(
            model_name='speechbubble',
            name='halftone_shadow',
            field=models.BooleanField(
                default=False,
                help_text='Enable halftone dot pattern shadow (western comics style)',
            ),
        ),
        # Update bubble_type choices to include new types
        migrations.AlterField(
            model_name='speechbubble',
            name='bubble_type',
            field=models.CharField(
                choices=[
                    ('oval', 'Standard Oval'),
                    ('thought', 'Thought Cloud'),
                    ('shout', 'Shout/Jagged'),
                    ('whisper', 'Whisper (dotted)'),
                    ('narrative', 'Narrative Box'),
                    ('caption', 'Caption'),
                    ('radio', 'Radio/Electronic'),
                    ('burst', 'Action Burst'),
                    ('flash', 'Manga Flash'),
                    ('wavy', 'Nervous/Wavy'),
                    ('angry', 'Angry Spikes'),
                    ('poof', 'Sound Effect'),
                    ('electric', 'Electric/Shock'),
                ],
                default='oval',
                max_length=20,
            ),
        ),
    ]
