# Generated by Django 5.2.6 on 2026-01-13 18:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rb_core', '0076_speech_bubble_style_system'),
    ]

    operations = [
        migrations.AddField(
            model_name='artworklibraryitem',
            name='is_derivative',
            field=models.BooleanField(default=False, help_text="True if artwork is derived from another collaborator's work"),
        ),
        migrations.AddField(
            model_name='artworklibraryitem',
            name='source_artwork',
            field=models.ForeignKey(blank=True, help_text='Original artwork this was derived from', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='derivatives', to='rb_core.artworklibraryitem'),
        ),
        migrations.AddField(
            model_name='collaboratorrole',
            name='contract_effective_date',
            field=models.DateTimeField(blank=True, help_text='When contract obligations begin (defaults to acceptance date if not set)', null=True),
        ),
        migrations.AddField(
            model_name='collaboratorrole',
            name='warranty_acknowledged_at',
            field=models.DateTimeField(blank=True, help_text='When warranty of originality was acknowledged', null=True),
        ),
        migrations.AddField(
            model_name='collaboratorrole',
            name='warranty_of_originality_acknowledged',
            field=models.BooleanField(default=False, help_text='Collaborator acknowledges their contributions are original work'),
        ),
        migrations.AddField(
            model_name='comicpanel',
            name='is_derivative',
            field=models.BooleanField(default=False, help_text="True if artwork is derived from another collaborator's work"),
        ),
        migrations.AddField(
            model_name='comicpanel',
            name='source_panel',
            field=models.ForeignKey(blank=True, help_text='Original panel this was derived from', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='derivatives', to='rb_core.comicpanel'),
        ),
        migrations.AddField(
            model_name='comicpanel',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, help_text='User who uploaded the current artwork', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_panels', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='projectsection',
            name='is_derivative',
            field=models.BooleanField(default=False, help_text="True if content is derived from another collaborator's work"),
        ),
        migrations.AddField(
            model_name='projectsection',
            name='parent_section',
            field=models.ForeignKey(blank=True, help_text='Original section this was derived from (for derivative tracking)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='derivatives', to='rb_core.projectsection'),
        ),
        migrations.AddField(
            model_name='projectsection',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, help_text='User who uploaded the current media file', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_sections', to=settings.AUTH_USER_MODEL),
        ),
    ]
