# Generated by Django 5.2.6 on 2026-01-13 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rb_core', '0077_collaboration_contract_framework'),
    ]

    operations = [
        migrations.AddField(
            model_name='collaboratorrole',
            name='breach_contested',
            field=models.BooleanField(default=False, help_text='Whether the collaborator has contested this breach'),
        ),
        migrations.AddField(
            model_name='collaboratorrole',
            name='breach_count',
            field=models.PositiveIntegerField(default=0, help_text='Cumulative count of breaches for this collaboration'),
        ),
        migrations.AddField(
            model_name='collaboratorrole',
            name='breach_cured_at',
            field=models.DateTimeField(blank=True, help_text='When the breach was cured (null if uncured)', null=True),
        ),
        migrations.AddField(
            model_name='collaboratorrole',
            name='breach_detected_at',
            field=models.DateTimeField(blank=True, help_text='When the current breach was detected', null=True),
        ),
        migrations.AddField(
            model_name='collaboratorrole',
            name='cure_actions_required',
            field=models.TextField(blank=True, help_text='Description of actions needed to cure the breach'),
        ),
        migrations.AddField(
            model_name='collaboratorrole',
            name='cure_deadline',
            field=models.DateTimeField(blank=True, help_text='Deadline to cure the breach', null=True),
        ),
        migrations.AddField(
            model_name='collaboratorrole',
            name='current_breach_severity',
            field=models.CharField(blank=True, choices=[('minor', 'Minor'), ('moderate', 'Moderate'), ('severe', 'Severe'), ('critical', 'Critical')], help_text='Severity level of current breach', max_length=20),
        ),
        migrations.AddField(
            model_name='collaboratorrole',
            name='current_breach_type',
            field=models.CharField(blank=True, choices=[('deadline', 'Deadline Breach'), ('quality', 'Quality Breach'), ('communication', 'Communication Breach'), ('abandonment', 'Abandonment'), ('scope', 'Scope Violation'), ('confidentiality', 'Confidentiality Breach')], help_text='Type of current active breach', max_length=20),
        ),
        migrations.AddField(
            model_name='contracttask',
            name='rejection_count',
            field=models.PositiveIntegerField(default=0, help_text='Number of times this task has been rejected (3+ triggers quality breach)'),
        ),
        migrations.AlterField(
            model_name='collaboratorrole',
            name='has_active_breach',
            field=models.BooleanField(default=False, help_text='Whether collaborator has an active breach'),
        ),
    ]
