# Generated by Django 5.2.6 on 2026-01-13 18:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rb_core', '0078_breach_system'),
    ]

    operations = [
        migrations.AddField(
            model_name='collaborativeproject',
            name='has_active_breach',
            field=models.BooleanField(default=False, help_text='Whether any collaborator has an uncured breach (blocks minting)'),
        ),
        migrations.AddField(
            model_name='collaborativeproject',
            name='has_active_dispute',
            field=models.BooleanField(default=False, help_text='Whether project has an active dispute (blocks minting)'),
        ),
        migrations.CreateModel(
            name='Dispute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('revenue', 'Revenue Dispute'), ('quality', 'Quality Dispute'), ('deadline', 'Deadline Dispute'), ('scope', 'Scope Dispute'), ('attribution', 'Attribution Dispute'), ('bad_faith', 'Bad Faith / Fraud')], help_text='Category of dispute', max_length=20)),
                ('level', models.PositiveIntegerField(choices=[(0, 'Self-Resolution'), (1, 'Structured Negotiation'), (2, 'Platform Mediation'), (3, 'Binding Resolution')], default=1, help_text='Current escalation level')),
                ('status', models.CharField(choices=[('open', 'Open'), ('negotiating', 'Negotiating'), ('mediating', 'Under Mediation'), ('binding', 'Binding Decision Pending'), ('resolved', 'Resolved'), ('withdrawn', 'Withdrawn')], default='open', max_length=20)),
                ('title', models.CharField(help_text='Brief title describing the dispute', max_length=200)),
                ('opener_position', models.TextField(help_text="Opening party's statement of the dispute")),
                ('respondent_position', models.TextField(blank=True, help_text="Respondent's statement/defense")),
                ('mediator_recommendation', models.TextField(blank=True, help_text="Platform mediator's non-binding recommendation")),
                ('final_decision', models.TextField(blank=True, help_text='Binding decision if escalated to level 3')),
                ('decision_by', models.CharField(blank=True, help_text="Who made the final decision (username or 'platform')", max_length=50)),
                ('opened_at', models.DateTimeField(auto_now_add=True)),
                ('escalated_at', models.DateTimeField(blank=True, help_text='When dispute was last escalated', null=True)),
                ('resolved_at', models.DateTimeField(blank=True, help_text='When dispute was resolved', null=True)),
                ('related_breach', models.BooleanField(default=False, help_text='Whether this dispute is from a contested breach')),
                ('opened_by', models.ForeignKey(help_text='User who opened the dispute', on_delete=django.db.models.deletion.CASCADE, related_name='disputes_opened', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(help_text='Project this dispute relates to', on_delete=django.db.models.deletion.CASCADE, related_name='disputes', to='rb_core.collaborativeproject')),
                ('respondent', models.ForeignKey(help_text='User the dispute is against', on_delete=django.db.models.deletion.CASCADE, related_name='disputes_against', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-opened_at'],
            },
        ),
        migrations.CreateModel(
            name='DisputeMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(help_text='Message content')),
                ('is_mediator', models.BooleanField(default=False, help_text='Whether this message is from platform mediator')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(help_text='Message author', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('dispute', models.ForeignKey(help_text='Parent dispute', on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='rb_core.dispute')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='dispute',
            index=models.Index(fields=['project', 'status'], name='rb_core_dis_project_013e26_idx'),
        ),
        migrations.AddIndex(
            model_name='dispute',
            index=models.Index(fields=['opened_by', 'status'], name='rb_core_dis_opened__38e8ee_idx'),
        ),
        migrations.AddIndex(
            model_name='dispute',
            index=models.Index(fields=['respondent', 'status'], name='rb_core_dis_respond_296d02_idx'),
        ),
    ]
