# Generated by Django 5.2.6 on 2026-01-19 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rb_core', '0080_purchaseintent_solana_tx_signature'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='has_seen_beta_welcome',
            field=models.BooleanField(default=False, help_text='Whether user has seen the beta welcome modal'),
        ),
    ]
