# Generated by Django 5.2.6 on 2026-01-20 21:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rb_core', '0081_beta_welcome_tracking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('invitation', 'Collaboration Invitation'), ('invitation_response', 'Invitation Response'), ('counter_proposal', 'Counter Proposal'), ('comment', 'Comment'), ('approval', 'Approval Status Change'), ('section_update', 'Section Update'), ('revenue_proposal', 'Revenue Split Proposal'), ('mint_ready', 'Project Ready for Minting'), ('content_like', 'Content Like'), ('content_comment', 'Content Comment'), ('content_rating', 'Content Rating'), ('creator_review', 'Creator Review'), ('content_purchase', 'Content Purchase')], db_index=True, max_length=20),
        ),
        migrations.CreateModel(
            name='BlockchainAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('nft_mint', 'NFT Mint'), ('usdc_distribute', 'USDC Distribution'), ('ipfs_upload', 'IPFS Upload'), ('payment_detected', 'Payment Detected'), ('treasury_reconciliation', 'Treasury Reconciliation'), ('wallet_creation', 'Wallet Creation'), ('refund', 'Refund'), ('retry', 'Retry Operation')], db_index=True, max_length=50)),
                ('status', models.CharField(choices=[('started', 'Started'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('retrying', 'Retrying')], db_index=True, default='started', max_length=20)),
                ('transaction_signature', models.CharField(blank=True, db_index=True, help_text='Solana transaction signature', max_length=128, null=True)),
                ('nft_mint_address', models.CharField(blank=True, help_text='NFT mint address if applicable', max_length=64, null=True)),
                ('from_wallet', models.CharField(blank=True, help_text='Source wallet address', max_length=64, null=True)),
                ('to_wallet', models.CharField(blank=True, help_text='Destination wallet address', max_length=64, null=True)),
                ('amount_usdc', models.DecimalField(blank=True, decimal_places=6, help_text='USDC amount involved in operation', max_digits=18, null=True)),
                ('gas_fee_usd', models.DecimalField(blank=True, decimal_places=6, help_text='Gas fee in USD', max_digits=10, null=True)),
                ('platform_fee_usdc', models.DecimalField(blank=True, decimal_places=6, help_text='Platform fee in USDC', max_digits=18, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional structured data (IPFS URIs, collaborator details, etc.)')),
                ('error_message', models.TextField(blank=True, help_text='Error message if operation failed', null=True)),
                ('error_code', models.CharField(blank=True, help_text='Error code or exception type', max_length=100, null=True)),
                ('celery_task_id', models.CharField(blank=True, help_text='Celery task ID for async operations', max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('completed_at', models.DateTimeField(blank=True, help_text='When the operation completed (success or failure)', null=True)),
                ('duration_ms', models.IntegerField(blank=True, help_text='Operation duration in milliseconds', null=True)),
                ('batch_purchase', models.ForeignKey(blank=True, help_text='Batch purchase associated with this operation', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blockchain_audit_logs', to='rb_core.batchpurchase')),
                ('purchase', models.ForeignKey(blank=True, help_text='Purchase associated with this operation', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blockchain_audit_logs', to='rb_core.purchase')),
                ('user', models.ForeignKey(blank=True, help_text='User associated with this operation (nullable for system tasks)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blockchain_audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Blockchain Audit Log',
                'verbose_name_plural': 'Blockchain Audit Logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['action', 'status', 'created_at'], name='rb_core_blo_action_6d3973_idx'), models.Index(fields=['user', 'created_at'], name='rb_core_blo_user_id_6d8439_idx'), models.Index(fields=['purchase', 'created_at'], name='rb_core_blo_purchas_f63f50_idx'), models.Index(fields=['transaction_signature'], name='rb_core_blo_transac_edc282_idx')],
            },
        ),
    ]
