# Generated by Django 5.2.6 on 2026-01-23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rb_core', '0082_alter_notification_notification_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comicpage',
            name='script_data',
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text='Structured script data for this page (description, panel scripts)'
            ),
        ),
    ]
