# Generated by Django 5.2.6

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rb_core', '0083_add_script_data_to_comicpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='collaborativeproject',
            name='reading_direction',
            field=models.CharField(
                max_length=3,
                choices=[
                    ('ltr', 'Left-to-Right (Western)'),
                    ('rtl', 'Right-to-Left (Manga)'),
                ],
                default='ltr',
                help_text='Reading direction for comic pages',
            ),
        ),
    ]
