# Generated by Django 5.2.6 on 2026-01-27 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rb_core', '0084_add_reading_direction_to_collaborativeproject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collaborativeproject',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('ready_for_mint', 'Ready for Mint'), ('minted', 'Minted'), ('unpublished', 'Unpublished'), ('cancelled', 'Cancelled')], default='draft', max_length=20),
        ),
        migrations.AlterField(
            model_name='content',
            name='inventory_status',
            field=models.CharField(choices=[('draft', 'Draft'), ('minted', 'Minted'), ('unpublished', 'Unpublished'), ('delisted', 'Delisted')], default='draft', max_length=16),
        ),
    ]
