# Generated by Django 5.2.6 on 2026-01-29 22:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rb_core', '0085_alter_collaborativeproject_status_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cartitem',
            unique_together={('cart', 'chapter'), ('cart', 'content')},
        ),
        migrations.AddField(
            model_name='cartitem',
            name='comic_issue',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to='rb_core.comicissue'),
        ),
        migrations.AddField(
            model_name='purchase',
            name='comic_issue',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='purchases', to='rb_core.comicissue'),
        ),
        migrations.AddField(
            model_name='purchaseintent',
            name='comic_issue',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='purchase_intents', to='rb_core.comicissue'),
        ),
        migrations.AlterUniqueTogether(
            name='cartitem',
            unique_together={('cart', 'chapter'), ('cart', 'comic_issue'), ('cart', 'content')},
        ),
        migrations.AddIndex(
            model_name='cartitem',
            index=models.Index(fields=['cart', 'comic_issue'], name='rb_core_car_cart_id_63902c_idx'),
        ),
    ]
