# Generated by Django 5.2.6 on 2026-01-30 07:52

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rb_core', '0086_alter_cartitem_unique_together_cartitem_comic_issue_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TierConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('founding_slots_total', models.PositiveIntegerField(default=50)),
                ('founding_slots_claimed', models.PositiveIntegerField(default=0)),
                ('founding_threshold', models.DecimalField(decimal_places=2, default=Decimal('100.00'), help_text='Project cumulative sales threshold to trigger founding qualification', max_digits=10)),
                ('level_thresholds', models.JSONField(default=dict, help_text="Mapping of level name to lifetime_project_sales threshold, e.g. {'level_1': 500}")),
                ('fee_rates', models.JSONField(default=dict, help_text="Mapping of tier name to fee rate as string decimal, e.g. {'founding': '0.01'}")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Tier Configuration',
                'verbose_name_plural': 'Tier Configuration',
            },
        ),
        migrations.AddField(
            model_name='collaborativeproject',
            name='founding_qualification_triggered',
            field=models.BooleanField(default=False, help_text='Whether this project has already triggered founding creator checks'),
        ),
        migrations.AddField(
            model_name='collaborativeproject',
            name='total_sales',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Cumulative sales revenue for this project', max_digits=14),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='lifetime_project_sales',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Cumulative full sale amount credited for ALL projects this creator participates in', max_digits=14),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='tier_qualified_at',
            field=models.DateTimeField(blank=True, help_text='When the creator last qualified for a tier upgrade', null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='tier',
            field=models.CharField(choices=[('founding', 'Founding Creator'), ('level_5', 'Level 5'), ('level_4', 'Level 4'), ('level_3', 'Level 3'), ('level_2', 'Level 2'), ('level_1', 'Level 1'), ('standard', 'Standard')], default='standard', max_length=16),
        ),
        migrations.CreateModel(
            name='FoundingCreatorSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('claimed_at', models.DateTimeField(auto_now_add=True)),
                ('qualifying_sale_amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='founding_slots', to='rb_core.collaborativeproject')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='founding_slots', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'project')},
            },
        ),
    ]
