# Generated by Django 5.2.6 on 2026-01-30 07:58

from django.db import migrations


def migrate_legacy_tiers(apps, schema_editor):
    """Convert old Basic/Pro/Elite tiers to the new standard tier."""
    UserProfile = apps.get_model('rb_core', 'UserProfile')
    updated = UserProfile.objects.filter(
        tier__in=['Basic', 'Pro', 'Elite']
    ).update(tier='standard')
    if updated:
        print(f'  Migrated {updated} profiles from legacy tiers to standard')


def reverse_migration(apps, schema_editor):
    """Reverse: set all standard tiers back to Basic."""
    UserProfile = apps.get_model('rb_core', 'UserProfile')
    UserProfile.objects.filter(tier='standard').update(tier='Basic')


class Migration(migrations.Migration):

    dependencies = [
        ('rb_core', '0087_tierconfiguration_and_more'),
    ]

    operations = [
        migrations.RunPython(migrate_legacy_tiers, reverse_migration),
    ]
