# Generated by Django 5.2.6 on 2026-02-12 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rb_core', '0088_migrate_legacy_tiers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coinbasetransaction',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('delayed', 'Delayed'), ('completed', 'Completed'), ('failed', 'Failed'), ('expired', 'Expired'), ('canceled', 'Canceled')], default='pending', max_length=20),
        ),
    ]
