# Generated by Django 5.2.6 on 2026-02-16 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rb_core', '0089_add_delayed_status_to_coinbase_transaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bridgecustomer',
            name='kyc_link',
            field=models.URLField(blank=True, help_text='KYC verification URL from Bridge', max_length=500),
        ),
    ]
