# Generated by Django 5.2.6 on 2026-02-24 07:48

from django.db import migrations, models


def convert_unpublished_to_delisted(apps, schema_editor):
    Content = apps.get_model('rb_core', 'Content')
    Content.objects.filter(inventory_status='unpublished').update(inventory_status='delisted')


class Migration(migrations.Migration):

    dependencies = [
        ('rb_core', '0090_increase_bridge_kyc_link_max_length'),
    ]

    operations = [
        migrations.RunPython(convert_unpublished_to_delisted, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='content',
            name='inventory_status',
            field=models.CharField(choices=[('draft', 'Draft'), ('minted', 'Minted'), ('delisted', 'Delisted')], default='draft', max_length=16),
        ),
    ]
