# Generated by Django 5.2.6 on 2026-02-24 23:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rb_core', '0091_standardize_inventory_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('invitation', 'Collaboration Invitation'), ('invitation_response', 'Invitation Response'), ('counter_proposal', 'Counter Proposal'), ('comment', 'Comment'), ('approval', 'Approval Status Change'), ('section_update', 'Section Update'), ('revenue_proposal', 'Revenue Split Proposal'), ('mint_ready', 'Project Ready for Minting'), ('content_like', 'Content Like'), ('content_comment', 'Content Comment'), ('content_rating', 'Content Rating'), ('creator_review', 'Creator Review'), ('content_purchase', 'Content Purchase'), ('new_follower', 'New Follower')], db_index=True, max_length=20),
        ),
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(max_length=20)),
                ('in_app', models.BooleanField(default=True)),
                ('email', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'notification_type')},
            },
        ),
    ]
