# Generated by Django 5.2.6 on 2026-03-27 05:57

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rb_core', '0092_alter_notification_notification_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='collaboratorrole',
            name='contract_type',
            field=models.CharField(choices=[('revenue_share', 'Revenue Share'), ('work_for_hire', 'Work for Hire'), ('hybrid', 'Hybrid')], default='revenue_share', help_text='Payment structure: revenue_share (existing), work_for_hire (milestone escrow), or hybrid (upfront + rev share)', max_length=20),
        ),
        migrations.AddField(
            model_name='collaboratorrole',
            name='escrow_funded_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Amount currently held in escrow (funded by project owner)', max_digits=10),
        ),
        migrations.AddField(
            model_name='collaboratorrole',
            name='escrow_funded_at',
            field=models.DateTimeField(blank=True, help_text='When escrow was fully funded', null=True),
        ),
        migrations.AddField(
            model_name='collaboratorrole',
            name='escrow_released_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Cumulative amount released from escrow to collaborator', max_digits=10),
        ),
        migrations.AddField(
            model_name='collaboratorrole',
            name='total_contract_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total agreed payment in USD for work_for_hire/hybrid contracts', max_digits=10),
        ),
        migrations.AddField(
            model_name='collaboratorrole',
            name='trust_pages_completed',
            field=models.PositiveIntegerField(default=0, help_text='Pages completed in trust-building phase (max 5)'),
        ),
        migrations.AddField(
            model_name='collaboratorrole',
            name='trust_phase',
            field=models.CharField(choices=[('not_started', 'Not Started'), ('trust_building', 'Trust Building'), ('production', 'Production'), ('completed', 'Completed')], default='not_started', help_text='Current phase of milestone progression', max_length=20),
        ),
        migrations.AddField(
            model_name='collaboratorrole',
            name='upfront_percentage',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='For hybrid: percentage of total paid upfront via escrow. Revenue share handles the rest.', max_digits=5),
        ),
        migrations.AddField(
            model_name='contracttask',
            name='auto_approve_deadline',
            field=models.DateTimeField(blank=True, help_text="When auto-approve triggers if writer hasn't reviewed", null=True),
        ),
        migrations.AddField(
            model_name='contracttask',
            name='auto_approved',
            field=models.BooleanField(default=False, help_text='Whether this task was auto-approved by timer expiration'),
        ),
        migrations.AddField(
            model_name='contracttask',
            name='escrow_release_status',
            field=models.CharField(choices=[('not_applicable', 'Not Applicable'), ('pending', 'Pending'), ('approved', 'Release Approved'), ('released', 'Released'), ('disputed', 'Disputed'), ('refunded', 'Refunded')], default='not_applicable', help_text='Status of escrow payment release for this task', max_length=20),
        ),
        migrations.AddField(
            model_name='contracttask',
            name='escrow_released_at',
            field=models.DateTimeField(blank=True, help_text='When escrow funds were released for this task', null=True),
        ),
        migrations.AddField(
            model_name='contracttask',
            name='milestone_type',
            field=models.CharField(choices=[('trust_page', 'Trust Phase - Single Page'), ('production_block', 'Production - Page Block'), ('final_delivery', 'Final Delivery'), ('custom', 'Custom Milestone')], default='custom', help_text='Type of milestone this task represents', max_length=20),
        ),
        migrations.AddField(
            model_name='contracttask',
            name='page_range_end',
            field=models.PositiveIntegerField(blank=True, help_text='Ending page number for page-based milestones', null=True),
        ),
        migrations.AddField(
            model_name='contracttask',
            name='page_range_start',
            field=models.PositiveIntegerField(blank=True, help_text='Starting page number for page-based milestones', null=True),
        ),
        migrations.AddField(
            model_name='contracttask',
            name='payment_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='USD amount released from escrow on sign-off', max_digits=10),
        ),
        migrations.AddField(
            model_name='contracttask',
            name='review_window_hours',
            field=models.PositiveIntegerField(default=72, help_text='Hours the writer has to review before auto-approve triggers'),
        ),
        migrations.AddField(
            model_name='contracttask',
            name='revision_limit',
            field=models.PositiveIntegerField(default=3, help_text='Maximum revisions before requiring contract amendment'),
        ),
        migrations.AddField(
            model_name='contracttask',
            name='revisions_used',
            field=models.PositiveIntegerField(default=0, help_text='Number of revisions consumed (increments on rejection)'),
        ),
        migrations.CreateModel(
            name='MilestoneTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="e.g., '22-Page Issue Standard'", max_length=100)),
                ('description', models.TextField(blank=True)),
                ('total_pages', models.PositiveIntegerField(default=22, help_text='Total pages this template covers')),
                ('milestones', models.JSONField(default=list, help_text='Ordered list of milestone definitions: [{type, pages, payment_pct, description, revision_limit, review_window_hours}]')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('role_definition', models.ForeignKey(help_text='Role this template applies to', on_delete=django.db.models.deletion.CASCADE, related_name='milestone_templates', to='rb_core.roledefinition')),
            ],
            options={
                'ordering': ['role_definition', 'name'],
            },
        ),
        migrations.CreateModel(
            name='EscrowTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('fund', 'Escrow Funded'), ('release', 'Milestone Release'), ('auto_release', 'Auto-Approve Release'), ('refund', 'Refund to Funder'), ('dispute_hold', 'Held for Dispute'), ('dispute_release', 'Released After Dispute')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('escrow_balance_after', models.DecimalField(decimal_places=2, help_text='Running escrow balance after this transaction', max_digits=10)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('collaborator_role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='escrow_transactions', to='rb_core.collaboratorrole')),
                ('contract_task', models.ForeignKey(blank=True, help_text='Specific task this transaction relates to (null for full-contract operations)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='escrow_transactions', to='rb_core.contracttask')),
                ('initiated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['collaborator_role', 'transaction_type'], name='rb_core_esc_collabo_ce6799_idx'), models.Index(fields=['contract_task'], name='rb_core_esc_contrac_0da489_idx')],
            },
        ),
    ]
