# Generated by Django 5.2.6 on 2026-03-28 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rb_core', '0093_escrow_system'),
    ]

    operations = [
        migrations.AddField(
            model_name='collaboratorrole',
            name='proposed_tasks',
            field=models.JSONField(blank=True, help_text='Counter-proposed task modifications: [{task_id, deadline, payment_amount}]', null=True),
        ),
        migrations.AddField(
            model_name='collaboratorrole',
            name='proposed_total_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Counter-proposed total contract amount for escrow contracts', max_digits=10, null=True),
        ),
    ]
