# Generated by Django 5.2.6 on 2026-03-28 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rb_core', '0094_counter_proposal_escrow_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='collaboratorrole',
            name='escrow_funding_deadline',
            field=models.DateTimeField(blank=True, help_text='Deadline for project owner to fund escrow. Work begins after funding.', null=True),
        ),
    ]
