# Generated by Django 5.2.6 on 2026-03-29 05:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rb_core', '0095_escrow_funding_deadline'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseintent',
            name='escrow_collaborator_role',
            field=models.ForeignKey(blank=True, help_text='The collaborator role being funded via escrow', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='escrow_funding_intents', to='rb_core.collaboratorrole'),
        ),
        migrations.AddField(
            model_name='purchaseintent',
            name='is_escrow_funding',
            field=models.BooleanField(default=False, help_text='True if this intent is for escrow funding (not a content purchase)'),
        ),
    ]
