# Generated by Django 5.2.6 on 2026-03-30 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rb_core', '0096_escrow_funding_intent'),
    ]

    operations = [
        migrations.AddField(
            model_name='escrowtransaction',
            name='artist_net_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Amount artist actually receives after fee', max_digits=10),
        ),
        migrations.AddField(
            model_name='escrowtransaction',
            name='platform_fee_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Platform fee portion (3% escrow service fee)', max_digits=10),
        ),
        migrations.AlterField(
            model_name='escrowtransaction',
            name='transaction_type',
            field=models.CharField(choices=[('fund', 'Escrow Funded'), ('release', 'Milestone Release'), ('auto_release', 'Auto-Approve Release'), ('platform_fee', 'Platform Fee'), ('refund', 'Refund to Funder'), ('dispute_hold', 'Held for Dispute'), ('dispute_release', 'Released After Dispute')], max_length=20),
        ),
    ]
