# Generated by Django 5.2.6 on 2026-03-30 20:12

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rb_core', '0097_escrow_fee_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='campaign_covers/')),
                ('content_type', models.CharField(choices=[('book', 'Book'), ('comic', 'Comic'), ('art', 'Art')], default='book', help_text='Content type for solo campaigns without a linked project', max_length=20)),
                ('campaign_type', models.CharField(choices=[('collaborative', 'Collaborative'), ('solo', 'Solo')], default='collaborative', max_length=20)),
                ('funding_goal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('current_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('backer_count', models.PositiveIntegerField(default=0)),
                ('deadline', models.DateTimeField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('funded', 'Funded'), ('transferred', 'Transferred'), ('failed', 'Failed'), ('reclaimable', 'Reclaimable'), ('reclaimed', 'Reclaimed'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('campaign_pda', models.CharField(blank=True, max_length=64)),
                ('campaign_pda_bump', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('funded_at', models.DateTimeField(blank=True, null=True)),
                ('escrow_creation_deadline', models.DateTimeField(blank=True, help_text='funded_at + 60 days. Auto-reclaim if no escrow created by this date.', null=True)),
                ('chapter_count', models.PositiveIntegerField(blank=True, help_text='For solo campaigns: number of chapters to release', null=True)),
                ('chapters_published', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_campaigns', to=settings.AUTH_USER_MODEL)),
                ('project', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campaign', to='rb_core.collaborativeproject')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CampaignContribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('reclaimed', 'Reclaimed'), ('transferred', 'Transferred')], default='pending', max_length=20)),
                ('transaction_signature', models.CharField(blank=True, max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('backer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaign_contributions', to=settings.AUTH_USER_MODEL)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contributions', to='rb_core.campaign')),
                ('purchase_intent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campaign_contributions', to='rb_core.purchaseintent')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CampaignUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='updates', to='rb_core.campaign')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='campaign',
            index=models.Index(fields=['status', 'deadline'], name='rb_core_cam_status_87da51_idx'),
        ),
        migrations.AddIndex(
            model_name='campaign',
            index=models.Index(fields=['creator', 'status'], name='rb_core_cam_creator_77555f_idx'),
        ),
        migrations.AddIndex(
            model_name='campaigncontribution',
            index=models.Index(fields=['campaign', 'status'], name='rb_core_cam_campaig_fa1075_idx'),
        ),
        migrations.AddIndex(
            model_name='campaigncontribution',
            index=models.Index(fields=['backer', 'campaign'], name='rb_core_cam_backer__4fce8c_idx'),
        ),
    ]
