# Generated by Django 5.2.6 on 2026-03-30 20:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rb_core', '0098_campaign_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='pitch_html',
            field=models.TextField(blank=True, help_text='Rich text campaign pitch (HTML). Displayed on the campaign detail page.'),
        ),
        migrations.CreateModel(
            name='CampaignMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='campaign_media/')),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='rb_core.campaign')),
            ],
            options={
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='CampaignTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(help_text='What backers get at this tier')),
                ('minimum_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('max_backers', models.PositiveIntegerField(blank=True, help_text='Optional limit on how many backers can claim this tier', null=True)),
                ('current_backers', models.PositiveIntegerField(default=0)),
                ('order', models.PositiveIntegerField(default=0)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tiers', to='rb_core.campaign')),
            ],
            options={
                'ordering': ['order', 'minimum_amount'],
            },
        ),
    ]
