# Generated by Django 5.2.6 on 2026-03-31 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rb_core', '0099_campaign_tiers_media_pitch'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='campaign',
            name='escrow_dormancy_deadline',
            field=models.DateTimeField(blank=True, help_text='Last milestone activity + 90 days. Return to campaign if exceeded.', null=True),
        ),
        migrations.AddField(
            model_name='campaign',
            name='escrow_pda',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='campaign',
            name='escrow_pda_bump',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('funded', 'Funded'), ('transferred', 'Transferred'), ('completed', 'Completed'), ('failed', 'Failed'), ('reclaimable', 'Reclaimable'), ('reclaimed', 'Reclaimed'), ('cancelled', 'Cancelled')], default='draft', max_length=20),
        ),
    ]
