# Generated by Django 5.2.6 on 2026-04-01 06:10

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rb_core', '0100_campaign_post_funding_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='collaborator_allocations',
            field=models.JSONField(blank=True, default=list, help_text='Per-collaborator funding breakdown for collaborative campaigns'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='production_costs',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text="Creator's production budget (printing, tools, etc.) — released directly to creator", max_digits=10),
        ),
    ]
