# Generated by Django 5.2.6 on 2026-04-02 05:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rb_core', '0101_campaign_collaborator_allocations'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageArtDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='art_deliveries/%Y/%m/')),
                ('filename', models.CharField(max_length=255)),
                ('file_size', models.PositiveIntegerField(default=0)),
                ('file_type', models.CharField(blank=True, max_length=100)),
                ('version', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('delivered', 'Delivered'), ('revision_requested', 'Revision Requested'), ('approved', 'Approved')], default='delivered', max_length=20)),
                ('revision_notes', models.TextField(blank=True, help_text="Author's notes when requesting revision")),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-version'],
            },
        ),
        migrations.CreateModel(
            name='PageReferenceImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='page_references/%Y/%m/')),
                ('thumbnail', models.FileField(blank=True, null=True, upload_to='page_references/thumbs/%Y/%m/')),
                ('caption', models.CharField(blank=True, max_length=500)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['sort_order', 'created_at'],
            },
        ),
        migrations.AddField(
            model_name='comicpage',
            name='page_status',
            field=models.CharField(choices=[('script_only', 'Script Only'), ('in_progress', 'In Progress'), ('art_delivered', 'Art Delivered'), ('revision_requested', 'Revision Requested'), ('approved', 'Approved')], default='script_only', help_text='Current workflow status of this page', max_length=20),
        ),
        migrations.AddField(
            model_name='projectcomment',
            name='comic_page',
            field=models.ForeignKey(blank=True, help_text='Optional: specific comic page this comment refers to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='page_comments', to='rb_core.comicpage'),
        ),
        migrations.AddIndex(
            model_name='projectcomment',
            index=models.Index(fields=['comic_page', '-created_at'], name='rb_core_pro_comic_p_1fae52_idx'),
        ),
        migrations.AddField(
            model_name='pageartdelivery',
            name='page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='art_deliveries', to='rb_core.comicpage'),
        ),
        migrations.AddField(
            model_name='pageartdelivery',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_art_deliveries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pageartdelivery',
            name='uploaded_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_art_deliveries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pagereferenceimage',
            name='page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reference_images', to='rb_core.comicpage'),
        ),
        migrations.AddField(
            model_name='pagereferenceimage',
            name='uploaded_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_reference_images', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='pageartdelivery',
            constraint=models.UniqueConstraint(fields=('page', 'version'), name='unique_page_art_version'),
        ),
    ]
