# Generated by Django 5.2.6 on 2026-04-02 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rb_core', '0102_workspace_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='cancel_tx_signature',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='campaign',
            name='on_chain_initialized',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='campaign',
            name='transfer_tx_signature',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='campaigncontribution',
            name='backer_record_pda',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='campaigncontribution',
            name='reclaim_tx_signature',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddConstraint(
            model_name='campaigncontribution',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['pending', 'confirmed', 'transferred'])), fields=('campaign', 'backer'), name='unique_active_campaign_backer'),
        ),
    ]
