# Generated by Django 5.2.6 on 2026-04-03 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rb_core', '0103_campaign_on_chain_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='avg_response_time_hours',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Average hours between task assignment and completion', max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='milestones_completed',
            field=models.PositiveIntegerField(default=0, help_text='Total signed-off contract tasks across all projects'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='on_time_delivery_rate',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='% of milestones delivered before deadline (0-100)', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='projects_completed',
            field=models.PositiveIntegerField(default=0, help_text='Collaborative projects fully completed'),
        ),
    ]
