# Generated by Django 5.2.6 on 2026-04-03 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rb_core', '0104_collaboration_reputation_stats'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collaborativeproject',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('complete', 'Complete'), ('ready_for_mint', 'Ready for Mint'), ('minted', 'Minted'), ('unpublished', 'Unpublished'), ('cancelled', 'Cancelled')], default='draft', max_length=20),
        ),
    ]
