# Generated by Django 5.2.6 on 2026-04-04 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rb_core', '0105_add_complete_project_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='projects_funded',
            field=models.PositiveIntegerField(default=0, help_text='Projects where user funded escrow'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='revisions_requested',
            field=models.PositiveIntegerField(default=0, help_text='Total revision requests made as project owner'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='total_escrow_funded_usd',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Total USD funded into escrow across all projects', max_digits=10),
        ),
    ]
