# Generated by Django 5.2.6 on 2026-04-04 07:14

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rb_core', '0106_add_owner_reputation_stats'),
    ]

    operations = [
        migrations.AddField(
            model_name='collaboratorrole',
            name='escrow_refunded_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Cumulative amount refunded from escrow to project owner', max_digits=10),
        ),
    ]
