# Generated by Django 5.2.6 on 2026-04-05 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rb_core', '0107_add_escrow_refunded_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='collaboratorrole',
            name='escrow_fee_mode',
            field=models.CharField(choices=[('writer_pays', 'Writer Pays'), ('artist_pays', 'Artist Pays'), ('split', 'Split')], default='writer_pays', help_text='Who absorbs the 3% escrow fee: writer (adds 3% on top), artist (deducted from payout), or split (1.5% each)', max_length=12),
        ),
    ]
