# Generated by Django 5.2.6 on 2026-04-05 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rb_core', '0108_add_escrow_fee_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='escrowtransaction',
            name='on_chain_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('submitted', 'Submitted'), ('confirmed', 'Confirmed'), ('failed', 'Failed'), ('skipped', 'Skipped — No Wallet')], default='pending', help_text='Status of the on-chain USDC transfer', max_length=20),
        ),
        migrations.AddField(
            model_name='escrowtransaction',
            name='solana_tx_signature',
            field=models.CharField(blank=True, default='', help_text='Solana transaction signature for on-chain USDC transfer', max_length=128),
        ),
        migrations.AddIndex(
            model_name='escrowtransaction',
            index=models.Index(fields=['solana_tx_signature'], name='rb_core_esc_solana__981120_idx'),
        ),
        migrations.AddIndex(
            model_name='escrowtransaction',
            index=models.Index(fields=['on_chain_status'], name='rb_core_esc_on_chai_e59ffa_idx'),
        ),
    ]
