# Generated by Django 5.2.6 on 2026-04-05 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rb_core', '0109_escrow_on_chain_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='collaboratorrole',
            name='escrow_initialized_tx',
            field=models.CharField(blank=True, default='', help_text='Solana tx signature of PDA initialization', max_length=128),
        ),
        migrations.AddField(
            model_name='collaboratorrole',
            name='escrow_pda_address',
            field=models.CharField(blank=True, default='', help_text='Solana PDA address of the escrow vault', max_length=64),
        ),
        migrations.AddField(
            model_name='collaboratorrole',
            name='escrow_pda_bump',
            field=models.PositiveSmallIntegerField(blank=True, help_text='PDA bump seed', null=True),
        ),
        migrations.AddField(
            model_name='collaboratorrole',
            name='escrow_vault_ata',
            field=models.CharField(blank=True, default='', help_text='ATA of the escrow PDA for USDC', max_length=64),
        ),
    ]
