# Generated by Django 5.2.6 on 2026-04-06 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rb_core', '0110_escrow_pda_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contracttask',
            name='status',
            field=models.CharField(choices=[('funded', 'Funded'), ('pending', 'Pending'), ('in_progress', 'In Progress'), ('submitted', 'Submitted'), ('under_review', 'Under Review'), ('revision_requested', 'Revision Requested'), ('resubmitted', 'Resubmitted'), ('approved', 'Approved'), ('released', 'Released'), ('complete', 'Complete'), ('deadline_passed', 'Deadline Passed'), ('extended', 'Extended'), ('stalled', 'Stalled'), ('final_rejection', 'Final Rejection'), ('reassigned', 'Reassigned'), ('refunded', 'Refunded'), ('cancelled', 'Cancelled'), ('signed_off', 'Signed Off')], default='pending', max_length=25),
        ),
    ]
