# Generated by Django 5.2.6 on 2026-04-06 05:51

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rb_core', '0111_expand_milestone_state_machine'),
    ]

    operations = [
        migrations.AddField(
            model_name='collaborativeproject',
            name='cancellation_hold_until',
            field=models.DateTimeField(blank=True, help_text='72hr hold for in-progress tasks before refund', null=True),
        ),
        migrations.AddField(
            model_name='collaborativeproject',
            name='cancellation_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='collaborativeproject',
            name='cancellation_requested_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='collaborativeproject',
            name='cancellation_requested_by',
            field=models.ForeignKey(blank=True, help_text='User who initiated cancellation', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cancellation_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='collaborativeproject',
            name='cancellation_type',
            field=models.CharField(blank=True, choices=[('writer', 'Writer Cancelled'), ('artist', 'Artist Cancelled'), ('mutual', 'Mutual Cancellation')], default='', max_length=10),
        ),
        migrations.AddField(
            model_name='collaboratorrole',
            name='completion_reserve_accumulated',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total reserve accumulated from released milestones', max_digits=10),
        ),
        migrations.AddField(
            model_name='collaboratorrole',
            name='completion_reserve_milestone_index',
            field=models.PositiveIntegerField(blank=True, help_text='PDA slot index for the reserve milestone', null=True),
        ),
        migrations.AddField(
            model_name='collaboratorrole',
            name='completion_reserve_pct',
            field=models.DecimalField(decimal_places=2, default=Decimal('10.00'), help_text='Percentage held back from each milestone (0-20%)', max_digits=4),
        ),
        migrations.AddField(
            model_name='collaboratorrole',
            name='completion_reserve_released',
            field=models.BooleanField(default=False, help_text='Whether the accumulated reserve has been released as bonus'),
        ),
        migrations.AddField(
            model_name='collaboratorrole',
            name='consecutive_auto_approvals',
            field=models.PositiveIntegerField(default=0, help_text='Count of consecutive auto-approved milestones (2+ = writer inactive)'),
        ),
        migrations.AddField(
            model_name='collaboratorrole',
            name='last_writer_activity',
            field=models.DateTimeField(blank=True, help_text='Last time the writer took an action on this project', null=True),
        ),
        migrations.AddField(
            model_name='collaboratorrole',
            name='writer_inactive_flagged',
            field=models.BooleanField(default=False, help_text='Whether writer has been flagged as inactive'),
        ),
        migrations.AddField(
            model_name='contracttask',
            name='deadline_action_taken',
            field=models.BooleanField(default=False, help_text='Whether writer has chosen extend/reassign/refund for this deadline breach'),
        ),
        migrations.AddField(
            model_name='contracttask',
            name='deadline_paused_at',
            field=models.DateTimeField(blank=True, help_text='When the deadline timer was paused (scope change)', null=True),
        ),
        migrations.AddField(
            model_name='contracttask',
            name='grace_deadline',
            field=models.DateTimeField(blank=True, help_text='48hr grace window after deadline_passed before auto-refund', null=True),
        ),
        migrations.AddField(
            model_name='contracttask',
            name='total_paused_seconds',
            field=models.PositiveIntegerField(default=0, help_text='Total seconds the deadline has been paused'),
        ),
        migrations.AddField(
            model_name='notification',
            name='action_options',
            field=models.JSONField(blank=True, default=list, help_text='Available actions: [{"key":"extend","label":"Extend Deadline","style":"primary"}]'),
        ),
        migrations.AddField(
            model_name='notification',
            name='action_required',
            field=models.BooleanField(default=False, help_text='Whether this notification requires user action'),
        ),
        migrations.AddField(
            model_name='notification',
            name='action_taken',
            field=models.CharField(blank=True, default='', help_text='Which action the user took', max_length=50),
        ),
        migrations.AddField(
            model_name='notification',
            name='action_taken_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='contract_task',
            field=models.ForeignKey(blank=True, help_text='Related contract task (for escrow notifications)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='rb_core.contracttask'),
        ),
        migrations.AddField(
            model_name='notification',
            name='expires_at',
            field=models.DateTimeField(blank=True, help_text='When this actionable notification expires', null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='projects_cancelled_as_artist',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='projects_cancelled_as_writer',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='contracttask',
            name='revision_limit',
            field=models.PositiveIntegerField(default=2, help_text='Maximum revisions before final rejection (configurable per task)'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('invitation', 'Collaboration Invitation'), ('invitation_response', 'Invitation Response'), ('counter_proposal', 'Counter Proposal'), ('comment', 'Comment'), ('approval', 'Approval Status Change'), ('section_update', 'Section Update'), ('revenue_proposal', 'Revenue Split Proposal'), ('mint_ready', 'Project Ready for Minting'), ('content_like', 'Content Like'), ('content_comment', 'Content Comment'), ('content_rating', 'Content Rating'), ('creator_review', 'Creator Review'), ('content_purchase', 'Content Purchase'), ('new_follower', 'New Follower'), ('milestone_submitted', 'Milestone Submitted'), ('milestone_approved', 'Milestone Approved'), ('milestone_rejected', 'Milestone Rejected'), ('escrow_released', 'Escrow Released'), ('escrow_refunded', 'Escrow Refunded'), ('deadline_warning', 'Deadline Warning'), ('deadline_passed', 'Deadline Passed'), ('grace_expiring', 'Grace Period Expiring'), ('final_rejection', 'Final Rejection'), ('rating_requested', 'Rating Requested'), ('scope_change', 'Scope Change Requested'), ('inactivity_warning', 'Inactivity Warning'), ('reassignment_offer', 'Reassignment Offer'), ('project_cancelled', 'Project Cancelled'), ('completion_bonus', 'Completion Bonus Released')], db_index=True, max_length=25),
        ),
        migrations.CreateModel(
            name='MilestoneExtension',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_deadline', models.DateTimeField()),
                ('new_deadline', models.DateTimeField()),
                ('extension_days', models.PositiveIntegerField()),
                ('reason', models.TextField(blank=True)),
                ('extension_type', models.CharField(choices=[('writer_granted', 'Writer Granted'), ('mutual', 'Mutual Agreement'), ('system_grace', 'System Grace Period')], default='writer_granted', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('contract_task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extensions', to='rb_core.contracttask')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MilestoneReassignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending_acceptance', 'Pending New Artist Acceptance'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('cancelled', 'Cancelled')], default='pending_acceptance', max_length=25)),
                ('reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('new_artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milestones_reassigned_to', to=settings.AUTH_USER_MODEL)),
                ('new_task', models.ForeignKey(blank=True, help_text='New ContractTask created for the replacement artist', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reassignments_to', to='rb_core.contracttask')),
                ('original_artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milestones_reassigned_from', to=settings.AUTH_USER_MODEL)),
                ('original_task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reassignments_from', to='rb_core.contracttask')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReputationScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('writer_score', models.DecimalField(decimal_places=2, default=Decimal('50.00'), max_digits=5)),
                ('writer_projects_completed', models.PositiveIntegerField(default=0)),
                ('writer_avg_review_time_hours', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=6)),
                ('writer_cancellation_rate', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5)),
                ('writer_auto_approve_rate', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5)),
                ('artist_score', models.DecimalField(decimal_places=2, default=Decimal('50.00'), max_digits=5)),
                ('artist_projects_completed', models.PositiveIntegerField(default=0)),
                ('artist_on_time_rate', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5)),
                ('artist_avg_quality_rating', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=3)),
                ('artist_avg_communication_rating', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=3)),
                ('artist_avg_timeliness_rating', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=3)),
                ('artist_stall_count', models.PositiveIntegerField(default=0)),
                ('artist_cancellation_rate', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5)),
                ('is_founding_creator', models.BooleanField(default=False, help_text='First 50 creators with $100+ completed escrow')),
                ('last_calculated', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reputation', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ScopeChangeRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(help_text='What exceeds the original brief')),
                ('status', models.CharField(choices=[('pending', 'Pending Writer Response'), ('withdrawn', 'Artist Withdrew Extra Scope'), ('amount_increased', 'Milestone Amount Increased'), ('new_milestone_added', 'New Milestone Added'), ('auto_resumed', 'Auto-Resumed (48hr timeout)')], default='pending', max_length=25)),
                ('additional_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Extra amount if writer chose to increase milestone', max_digits=10, null=True)),
                ('auto_resume_at', models.DateTimeField(blank=True, help_text="48hr after creation — timer auto-resumes if writer doesn't respond", null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('contract_task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scope_changes', to='rb_core.contracttask')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MilestoneRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quality_score', models.PositiveSmallIntegerField(help_text='Quality of work (artist) or clarity of brief (writer)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('communication_score', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('timeliness_score', models.PositiveSmallIntegerField(help_text='On-time delivery (artist) or responsiveness (writer)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('private_note', models.TextField(blank=True, help_text='Private feedback — visible only after project completes')),
                ('is_visible', models.BooleanField(default=False, help_text='Becomes True when project completes — prevents retaliatory mid-project ratings')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('contract_task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milestone_ratings', to='rb_core.contracttask')),
                ('rated_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milestone_ratings_received', to=settings.AUTH_USER_MODEL)),
                ('rater', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milestone_ratings_given', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('contract_task', 'rater')},
            },
        ),
    ]
