# Generated by Django 5.2.6 on 2026-04-06 19:17

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rb_core', '0112_escrow_lifecycle_models'),
    ]

    operations = [
        migrations.CreateModel(
            name='BackerContentAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('granted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CampaignRoleInterest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_name', models.CharField(max_length=100)),
                ('message', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('declined', 'Declined')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StretchGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('threshold_amount', models.DecimalField(decimal_places=2, help_text='Amount raised that triggers this stretch goal', max_digits=10)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('reached', models.BooleanField(default=False)),
                ('reached_at', models.DateTimeField(blank=True, null=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['sort_order', 'threshold_amount'],
            },
        ),
        migrations.RemoveConstraint(
            model_name='campaigncontribution',
            name='unique_active_campaign_backer',
        ),
        migrations.AddField(
            model_name='campaign',
            name='allow_overfunding',
            field=models.BooleanField(default=True, help_text='Whether to accept contributions beyond the funding goal'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, help_text='When creator cancelled the campaign', null=True),
        ),
        migrations.AddField(
            model_name='campaign',
            name='closed_at',
            field=models.DateTimeField(blank=True, help_text='When campaign officially stopped accepting backers', null=True),
        ),
        migrations.AddField(
            model_name='campaign',
            name='max_overfunding_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Cap on overfunding amount above goal (null = no cap)', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='campaign',
            name='previous_campaign',
            field=models.ForeignKey(blank=True, help_text='Link to a previous campaign (e.g., Issue #1 → Issue #2)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sequel_campaigns', to='rb_core.campaign'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='production_start_deadline_days',
            field=models.PositiveIntegerField(default=30, help_text='Days after funding to begin production before auto-refund triggers'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='role_assignment_deadline_days',
            field=models.PositiveIntegerField(default=60, help_text='Days after funding to fill all open roles before unfilled role milestones refund'),
        ),
        migrations.AddField(
            model_name='campaigncontribution',
            name='percentage_of_total',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text="Backer's share of total raised — used for proportional refunds", max_digits=5),
        ),
        migrations.AddField(
            model_name='campaigncontribution',
            name='refund_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Actual refund amount (may differ from contribution in partial refund scenarios)', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='campaigncontribution',
            name='refunded',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='campaigncontribution',
            name='refunded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='campaigncontribution',
            name='reward_tier',
            field=models.ForeignKey(blank=True, help_text='Selected reward tier', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contributions', to='rb_core.campaigntier'),
        ),
        migrations.AddField(
            model_name='campaigncontribution',
            name='withdrawn',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='campaigncontribution',
            name='withdrawn_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='campaigntier',
            name='custom_rewards',
            field=models.JSONField(blank=True, default=list, help_text='Custom tier perks'),
        ),
        migrations.AddField(
            model_name='campaigntier',
            name='fulfillment_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('fulfilled', 'Fulfilled')], default='pending', max_length=15),
        ),
        migrations.AddField(
            model_name='campaigntier',
            name='includes_credits',
            field=models.BooleanField(default=False, help_text='Backer name in credits'),
        ),
        migrations.AddField(
            model_name='campaigntier',
            name='includes_digital_copy',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='campaigntier',
            name='includes_early_access',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='campaigntier',
            name='includes_print_copy',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='collaborativeproject',
            name='is_campaign_funded',
            field=models.BooleanField(default=False, help_text='True if this project was funded via a campaign (refunds go to PDA1, not creator)'),
        ),
        migrations.AddField(
            model_name='notification',
            name='campaign',
            field=models.ForeignKey(blank=True, help_text='Related campaign (for campaign notifications)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='rb_core.campaign'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('invitation', 'Collaboration Invitation'), ('invitation_response', 'Invitation Response'), ('counter_proposal', 'Counter Proposal'), ('comment', 'Comment'), ('approval', 'Approval Status Change'), ('section_update', 'Section Update'), ('revenue_proposal', 'Revenue Split Proposal'), ('mint_ready', 'Project Ready for Minting'), ('content_like', 'Content Like'), ('content_comment', 'Content Comment'), ('content_rating', 'Content Rating'), ('creator_review', 'Creator Review'), ('content_purchase', 'Content Purchase'), ('new_follower', 'New Follower'), ('milestone_submitted', 'Milestone Submitted'), ('milestone_approved', 'Milestone Approved'), ('milestone_rejected', 'Milestone Rejected'), ('escrow_released', 'Escrow Released'), ('escrow_refunded', 'Escrow Refunded'), ('deadline_warning', 'Deadline Warning'), ('deadline_passed', 'Deadline Passed'), ('grace_expiring', 'Grace Period Expiring'), ('final_rejection', 'Final Rejection'), ('rating_requested', 'Rating Requested'), ('scope_change', 'Scope Change Requested'), ('inactivity_warning', 'Inactivity Warning'), ('reassignment_offer', 'Reassignment Offer'), ('project_cancelled', 'Project Cancelled'), ('completion_bonus', 'Completion Bonus Released'), ('campaign_backed', 'Campaign Backed'), ('campaign_funded', 'Campaign Funded'), ('campaign_failed', 'Campaign Failed'), ('campaign_refund', 'Campaign Refund Processed'), ('campaign_partial_refund', 'Campaign Partial Refund'), ('campaign_prod_update', 'Campaign Production Update'), ('campaign_complete', 'Campaign Complete'), ('campaign_stretch_hit', 'Stretch Goal Reached'), ('backer_content_access', 'Backer Content Access'), ('campaign_launched', 'Campaign Launched'), ('campaign_new_backer', 'New Campaign Backer'), ('campaign_withdrew', 'Backer Withdrew'), ('campaign_goal_reached', 'Campaign Goal Reached'), ('campaign_closed', 'Campaign Closed'), ('campaign_role_interest', 'Role Interest Received'), ('campaign_role_warn', 'Role Assignment Deadline Warning'), ('campaign_role_refund', 'Role Milestones Refunded'), ('campaign_role_avail', 'Campaign Role Available'), ('campaign_assigned', 'Campaign Role Assigned'), ('campaign_prod_start', 'Campaign Production Started'), ('campaign_team_joined', 'Team Member Joined'), ('campaign_team_complete', 'Team Complete')], db_index=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='notificationpreference',
            name='notification_type',
            field=models.CharField(max_length=40),
        ),
        migrations.AddConstraint(
            model_name='campaigncontribution',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['pending', 'confirmed', 'transferred']), ('withdrawn', False)), fields=('campaign', 'backer'), name='unique_active_campaign_backer'),
        ),
        migrations.AddField(
            model_name='backercontentaccess',
            name='contribution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_access', to='rb_core.campaigncontribution'),
        ),
        migrations.AddField(
            model_name='backercontentaccess',
            name='milestone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='backer_access_grants', to='rb_core.contracttask'),
        ),
        migrations.AddField(
            model_name='campaignroleinterest',
            name='campaign',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_interests', to='rb_core.campaign'),
        ),
        migrations.AddField(
            model_name='campaignroleinterest',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaign_role_interests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='stretchgoal',
            name='campaign',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stretch_goals', to='rb_core.campaign'),
        ),
        migrations.AddField(
            model_name='stretchgoal',
            name='linked_milestones',
            field=models.ManyToManyField(blank=True, help_text='Milestones added to PDA2 when this stretch goal is hit', related_name='stretch_goals', to='rb_core.contracttask'),
        ),
        migrations.AlterUniqueTogether(
            name='backercontentaccess',
            unique_together={('contribution', 'milestone')},
        ),
        migrations.AlterUniqueTogether(
            name='campaignroleinterest',
            unique_together={('campaign', 'user', 'role_name')},
        ),
    ]
