# Generated by Django 5.2.6 on 2026-04-06 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rb_core', '0113_campaign_system_extension'),
    ]

    operations = [
        migrations.AddField(
            model_name='contracttask',
            name='deadline_days_after_funding',
            field=models.PositiveIntegerField(blank=True, help_text='Days after escrow funding that this milestone is due. Used for campaign-funded projects.', null=True),
        ),
        migrations.AlterField(
            model_name='contracttask',
            name='deadline',
            field=models.DateTimeField(blank=True, help_text='Absolute deadline for task completion (computed from days_after_funding for campaign projects)', null=True),
        ),
    ]
