# Generated by Django 5.2.6 on 2026-04-06 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rb_core', '0114_campaign_relative_deadlines'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='campaigncontribution',
            name='unique_active_campaign_backer',
        ),
        migrations.AddConstraint(
            model_name='campaigncontribution',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'pending'), ('withdrawn', False)), fields=('campaign', 'backer'), name='unique_active_campaign_backer'),
        ),
    ]
