# Generated by Django 5.2.6 on 2026-04-07 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rb_core', '0115_fix_campaign_backer_constraint'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='campaigns_created',
            field=models.PositiveIntegerField(default=0, help_text='Campaigns created by this user'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='campaigns_failed',
            field=models.PositiveIntegerField(default=0, help_text='Campaigns that failed or were cancelled'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='campaigns_successful',
            field=models.PositiveIntegerField(default=0, help_text='Campaigns that reached funded/transferred/completed'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='total_campaign_raised_usd',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Total USDC raised across all campaigns', max_digits=12),
        ),
    ]
