# Generated by Django 5.2.6 on 2026-04-07 22:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rb_core', '0116_campaign_reputation_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='collaborativeproject',
            name='workspace_setup_complete',
            field=models.BooleanField(default=False, help_text='Author has completed workspace setup (all pages have briefs)'),
        ),
        migrations.AddField(
            model_name='collaborativeproject',
            name='workspace_setup_completed_at',
            field=models.DateTimeField(blank=True, help_text='When workspace setup was marked complete', null=True),
        ),
        migrations.AddField(
            model_name='comicpage',
            name='brief_complete',
            field=models.BooleanField(default=False, help_text='Author has finished writing the description/references for this page'),
        ),
        migrations.AddField(
            model_name='comicpage',
            name='milestone',
            field=models.ForeignKey(blank=True, help_text='The milestone/contract task this page belongs to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linked_pages', to='rb_core.contracttask'),
        ),
        migrations.AlterField(
            model_name='comicpage',
            name='page_status',
            field=models.CharField(choices=[('setup', 'Setup'), ('ready', 'Ready'), ('funded', 'Funded'), ('script_only', 'Script Only'), ('in_progress', 'In Progress'), ('art_delivered', 'Art Delivered'), ('revision_requested', 'Revision Requested'), ('approved', 'Approved')], default='script_only', help_text='Current workflow status of this page', max_length=20),
        ),
    ]
