# Generated by Django 5.2.6 on 2026-04-08 16:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rb_core', '0117_workspace_milestone_linking'),
    ]

    operations = [
        migrations.AddField(
            model_name='contracttask',
            name='depends_on',
            field=models.ForeignKey(blank=True, help_text='Milestone that must complete before this one unlocks', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dependents', to='rb_core.contracttask'),
        ),
        migrations.CreateModel(
            name='ProductionStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('order', models.PositiveIntegerField(default=0, help_text='Sequential order: 1=first stage, 2=second, etc.')),
                ('price_per_page', models.DecimalField(blank=True, decimal_places=2, help_text='Price per page for this stage (used to auto-calculate milestone amounts)', max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('collaborator_role', models.ForeignKey(blank=True, help_text='Who handles this stage', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='production_stages', to='rb_core.collaboratorrole')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='production_stages', to='rb_core.collaborativeproject')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('project', 'order')},
            },
        ),
        migrations.AddField(
            model_name='comicpage',
            name='current_stage',
            field=models.ForeignKey(blank=True, help_text='Which production stage this page is currently in', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='active_pages', to='rb_core.productionstage'),
        ),
        migrations.AddField(
            model_name='contracttask',
            name='stage',
            field=models.ForeignKey(blank=True, help_text='Which production stage this milestone belongs to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='milestones', to='rb_core.productionstage'),
        ),
    ]
