# Generated by Django 5.2.6 on 2026-04-09 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rb_core', '0118_production_stages'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='campaign_pda_closed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='campaign',
            name='campaign_pda_closed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='campaign',
            name='campaign_rent_recovered_lamports',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='collaborativeproject',
            name='escrow_closed',
            field=models.BooleanField(default=False, help_text='All escrow PDAs closed and rent recovered'),
        ),
        migrations.AddField(
            model_name='collaborativeproject',
            name='escrow_closed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='collaborativeproject',
            name='rent_recovered_lamports',
            field=models.BigIntegerField(blank=True, help_text='SOL rent recovered from closing PDAs', null=True),
        ),
    ]
