# Generated by Django 5.2.6 on 2026-04-10 21:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rb_core', '0119_pda_close_tracking'),
    ]

    operations = [
        migrations.AddField(
            model_name='collaborativeproject',
            name='character_designs_approved',
            field=models.BooleanField(default=False, help_text='Whether character designs have been approved (gates page workspace)'),
        ),
        migrations.AddField(
            model_name='collaborativeproject',
            name='escrow_funding_deadline_auto',
            field=models.DateTimeField(blank=True, help_text='14 days after contract acceptance — auto-expires if unfunded', null=True),
        ),
        migrations.AddField(
            model_name='collaborativeproject',
            name='mutual_cancellation_agreed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='collaborativeproject',
            name='mutual_cancellation_agreed_by',
            field=models.ForeignKey(blank=True, help_text='User who agreed to mutual cancellation', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mutual_cancellation_agreements', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='collaborativeproject',
            name='mutual_cancellation_requested_by',
            field=models.ForeignKey(blank=True, help_text='User who initiated mutual cancellation request', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mutual_cancellation_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='collaborativeproject',
            name='storyboard_thumbnails_approved',
            field=models.BooleanField(default=False, help_text='Whether storyboard thumbnails have been approved (gates production milestones)'),
        ),
        migrations.AddField(
            model_name='contracttask',
            name='cancellation_category',
            field=models.CharField(blank=True, choices=[('before_work', 'Before Work Started'), ('during_active_work', 'During Active Work'), ('post_preproduction', 'Post Pre-Production Approval'), ('mutual', 'Mutual Cancellation')], default='', help_text='Category of cancellation for reputation tracking', max_length=25),
        ),
        migrations.AddField(
            model_name='contracttask',
            name='cancellation_fee_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Fee paid to artist on post-pre-production cancellation', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='contracttask',
            name='cancellation_window_end',
            field=models.DateTimeField(blank=True, help_text='When the 24hr cancellation window closes', null=True),
        ),
        migrations.AddField(
            model_name='contracttask',
            name='cancellation_window_start',
            field=models.DateTimeField(blank=True, help_text='When the 24hr cancellation window opened (task became in_progress)', null=True),
        ),
        migrations.AddField(
            model_name='contracttask',
            name='previous_rejection_issues',
            field=models.JSONField(blank=True, default=list, help_text='Issue keywords from prior rejections for scope-change detection'),
        ),
        migrations.AddField(
            model_name='contracttask',
            name='review_escalation_sent_100',
            field=models.BooleanField(default=False, help_text='100% review window notification sent'),
        ),
        migrations.AddField(
            model_name='contracttask',
            name='review_escalation_sent_50',
            field=models.BooleanField(default=False, help_text='50% review window notification sent'),
        ),
        migrations.AddField(
            model_name='contracttask',
            name='review_escalation_sent_75',
            field=models.BooleanField(default=False, help_text='75% review window notification sent'),
        ),
        migrations.AddField(
            model_name='productionstage',
            name='depends_on_stage',
            field=models.ForeignKey(blank=True, help_text='Stage that must complete before this one can begin', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dependent_stages', to='rb_core.productionstage'),
        ),
        migrations.AddField(
            model_name='productionstage',
            name='is_billable',
            field=models.BooleanField(default=True, help_text='If True, creates a paid ContractTask. If False, approval checkpoint only.'),
        ),
        migrations.AddField(
            model_name='productionstage',
            name='stage_category',
            field=models.CharField(choices=[('pre_production', 'Pre-Production'), ('production', 'Production')], default='production', help_text='Whether this is a pre-production or production stage', max_length=20),
        ),
        migrations.AddField(
            model_name='reputationscore',
            name='artist_avg_delivery_speed_days',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Avg days before(-)/after(+) deadline artist delivers', max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='reputationscore',
            name='artist_cancellations_before_work',
            field=models.PositiveIntegerField(default=0, help_text='Cancellations before work started'),
        ),
        migrations.AddField(
            model_name='reputationscore',
            name='artist_cancellations_during_work',
            field=models.PositiveIntegerField(default=0, help_text='Cancellations while work was in progress'),
        ),
        migrations.AddField(
            model_name='reputationscore',
            name='artist_final_rejection_count',
            field=models.PositiveIntegerField(default=0, help_text='Milestones that hit final rejection'),
        ),
        migrations.AddField(
            model_name='reputationscore',
            name='artist_preproduction_delivery_rate',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='% of pre-production deliverables completed on time', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='reputationscore',
            name='artist_revision_rate',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='% of milestones requiring revisions', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='reputationscore',
            name='artist_scope_change_flags',
            field=models.PositiveIntegerField(default=0, help_text='Scope change flags raised by this artist'),
        ),
        migrations.AddField(
            model_name='reputationscore',
            name='mutual_cancellation_count',
            field=models.PositiveIntegerField(default=0, help_text='Projects mutually cancelled'),
        ),
        migrations.AddField(
            model_name='reputationscore',
            name='repeat_collaboration_count',
            field=models.PositiveIntegerField(default=0, help_text='Distinct users collaborated with on 2+ projects'),
        ),
        migrations.AddField(
            model_name='reputationscore',
            name='writer_avg_communication_rating',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Avg communication score from artist ratings', max_digits=3, null=True),
        ),
        migrations.AddField(
            model_name='reputationscore',
            name='writer_avg_escrow_funding_delay_hours',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Avg hours between contract acceptance and escrow funding', max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='reputationscore',
            name='writer_avg_rejection_clarity',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Avg quality score from artist ratings of rejection clarity (1-5)', max_digits=3, null=True),
        ),
        migrations.AddField(
            model_name='reputationscore',
            name='writer_campaigns_funded_never_started',
            field=models.PositiveIntegerField(default=0, help_text='Campaigns funded but production never began'),
        ),
        migrations.AddField(
            model_name='reputationscore',
            name='writer_grace_period_cancellations',
            field=models.PositiveIntegerField(default=0, help_text='Milestones cancelled during 24hr window'),
        ),
        migrations.AddField(
            model_name='reputationscore',
            name='writer_post_preproduction_cancellations',
            field=models.PositiveIntegerField(default=0, help_text='Projects cancelled after pre-production approved'),
        ),
        migrations.AddField(
            model_name='reputationscore',
            name='writer_projects_ended_early',
            field=models.PositiveIntegerField(default=0, help_text='Projects where not all milestones were completed'),
        ),
        migrations.AddField(
            model_name='reputationscore',
            name='writer_scope_change_requests',
            field=models.PositiveIntegerField(default=0, help_text='Scope change requests initiated as writer'),
        ),
        migrations.AlterField(
            model_name='contracttask',
            name='milestone_type',
            field=models.CharField(choices=[('trust_page', 'Trust Phase - Single Page'), ('production_block', 'Production - Page Block'), ('final_delivery', 'Final Delivery'), ('pre_production', 'Pre-Production'), ('custom', 'Custom Milestone')], default='custom', help_text='Type of milestone this task represents', max_length=20),
        ),
        migrations.CreateModel(
            name='PreProductionDeliverable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deliverable_type', models.CharField(choices=[('character_design', 'Character Design'), ('storyboard_thumbnail', 'Storyboard Thumbnail'), ('other', 'Other')], default='other', max_length=25)),
                ('title', models.CharField(max_length=200)),
                ('file', models.FileField(blank=True, null=True, upload_to='pre_production/')),
                ('version', models.PositiveIntegerField(default=1)),
                ('deadline', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('uploaded', 'Uploaded'), ('under_review', 'Under Review'), ('approved', 'Approved'), ('revision_requested', 'Revision Requested')], default='pending', max_length=20)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('revision_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pre_production_approvals', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pre_production_deliverables', to='rb_core.collaborativeproject')),
                ('stage', models.ForeignKey(help_text='Pre-production stage this deliverable belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='deliverables', to='rb_core.productionstage')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pre_production_uploads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['stage__order', 'created_at'],
            },
        ),
    ]
