"""
Django settings for renaissBlock project.

Generated by 'django-admin startproject' using Django 5.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os  # For environment variables and paths (PEP 8 compliant)

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-your-secret-key-here'  # Change this in production; never store in repo (per GUIDELINES.md Security Focus)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []  # Update for production


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rb_core',  # Custom app for core functionality (avoids conflict with Python's 'core' module)
    'rest_framework',  # For building APIs (e.g., content upload FR4, fiat callbacks FR2)
    'allauth',
    'allauth.account',
    # Future: Add apps for integrations like 'rest_framework' for APIs (FR2, FR4 in REQUIREMENTS.md)
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'allauth.account.middleware.AccountMiddleware',  # Required for allauth auth (FR3)
    # Security: Add rate limiting later (GUIDELINES.md)
]

ROOT_URLCONF = 'renaissBlock.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'renaissBlock.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases
# Using SQLite for MVP to avoid costs (per SCOPE.md constraints); switch to Postgres later (ARCHITECTURE.md)
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),  # Local file-based DB
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Security Settings (per GUIDELINES.md)
SECURE_SSL_REDIRECT = False  # Enable in production for HTTPS (TLS 1.3+)
SECURE_HSTS_SECONDS = 0  # Enable HSTS in production
SECURE_CONTENT_TYPE_NOSNIFF = True
SECURE_BROWSER_XSS_FILTER = True
X_FRAME_OPTIONS = 'DENY'
# CSP: To be configured for XSS protection
# No private key storage - rely on Web3Auth (FR3 in REQUIREMENTS.md)

# Placeholder for Integrations (per ARCHITECTURE.md)
# WEB3AUTH_CLIENT_ID = os.getenv('WEB3AUTH_CLIENT_ID')  # Set in env for keyless auth
# RAMP_API_KEY = os.getenv('RAMP_API_KEY')  # For fiat-to-crypto (FR2)
# IPFS_API_URL = 'https://ipfs.infura.io:5001'  # Free tier for decentralized storage (FR4, FR5)

# Future Expansion: Add moderation queue, analytics (FR7), collaboration logic (FR8)
# Ensure compliance with regulations (e.g., GDPR minimization) - no unnecessary data storage

AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
    'allauth.account.auth_backends.AuthenticationBackend',
]

SITE_ID = 1  # Required for allauth
ACCOUNT_LOGIN_METHODS = {'username': True}  # Replaces ACCOUNT_AUTHENTICATION_METHOD
ACCOUNT_SIGNUP_FIELDS = ['username', 'password1*', 'password2*']  # Replaces EMAIL_REQUIRED/USERNAME_REQUIRED = False
ACCOUNT_EMAIL_VERIFICATION = 'none'  # Optional for MVP
# Future: Add Web3Auth provider for seamless wallet auth
