"""
Django settings for renaissBlock project.

Generated by 'django-admin startproject' using Django 5.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
from decimal import Decimal
import os  # For environment variables and paths (PEP 8 compliant)
import dj_database_url  # For parsing DATABASE_URL in production

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load environment variables from backend/.env if present
try:
    from dotenv import load_dotenv  # type: ignore
    load_dotenv(BASE_DIR / '.env')
except Exception:
    pass

# Ensure Django looks for project-level templates (e.g., themed allauth pages)
try:
    TEMPLATES[0]['DIRS'] = [BASE_DIR / 'templates']
except Exception:
    pass

# Template overrides (ensure project-level templates are used)
try:
    import os as _os
    TEMPLATES[0]['DIRS'] = [str(BASE_DIR / 'templates')]
    TEMPLATES[0]['APP_DIRS'] = True
except Exception:
    pass


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('DJANGO_SECRET_KEY')
if not SECRET_KEY:
    raise ValueError(
        'DJANGO_SECRET_KEY environment variable must be set. '
        'Generate one with: python -c "from django.core.management.utils import get_random_secret_key; print(get_random_secret_key())"'
    )

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DEBUG', 'False').lower() in ('true', '1', 'yes')

# Beta Mode Settings
BETA_MODE = os.getenv('BETA_MODE', 'false').lower() in ('true', '1', 'yes')
ENVIRONMENT = os.getenv('ENVIRONMENT', 'development')

# ALLOWED_HOSTS - Configure for production
ALLOWED_HOSTS = os.getenv('ALLOWED_HOSTS', '127.0.0.1,localhost').split(',')

# Beta Mode Configuration
if BETA_MODE:
    # Add production domains for beta testing
    ALLOWED_HOSTS.extend(['renaissblock.com', 'api.renaissblock.com', 'www.renaissblock.com'])

# Production: Always allow production domains when DEBUG=False
if not DEBUG:
    production_hosts = ['renaissblock.com', 'api.renaissblock.com', 'www.renaissblock.com', '.renaissblock.com']
    for host in production_hosts:
        if host not in ALLOWED_HOSTS:
            ALLOWED_HOSTS.append(host)

    # Stripe test mode flag
    STRIPE_TEST_MODE = True

    # Email backend for beta (SMTP for real emails)
    if os.getenv('EMAIL_BACKEND'):
        EMAIL_BACKEND = os.getenv('EMAIL_BACKEND')

    # Beta-specific logging or features can be added here
    # Example: More verbose logging, special beta user tracking, etc.


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'cloudinary_storage',  # Must be before staticfiles for media storage
    'django.contrib.staticfiles',
    'django.contrib.sites',
    'cloudinary',  # Cloudinary integration for media files
    'rb_core',  # Custom app for core functionality (avoids conflict with Python's 'core' module)
    'rest_framework',  # For building APIs (e.g., content upload FR4, fiat callbacks FR2)
    'allauth',
    'allauth.account',
    'corsheaders',
    # Future: Add apps for integrations like 'rest_framework' for APIs (FR2, FR4 in REQUIREMENTS.md)
]

# Use custom user model from rb_core for auth (FR3)
AUTH_USER_MODEL = 'rb_core.User'

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'allauth.account.middleware.AccountMiddleware',
    'rb_core.middleware.SimpleCSPMiddleware',
]

ROOT_URLCONF = 'renaissBlock.urls'

# Disable automatic trailing slash redirects (prevents 307 on webhook endpoints)
APPEND_SLASH = False

# Template configuration
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [str(BASE_DIR / 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'renaissBlock.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases
# Supports both SQLite (dev) and PostgreSQL (production) based on environment
if os.getenv('DATABASE_URL'):
    # Production: PostgreSQL (Railway/Heroku style DATABASE_URL)
    DATABASES = {
        'default': dj_database_url.parse(os.getenv('DATABASE_URL'))
    }
else:
    # Development: SQLite
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
        }
    }


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators
# Strengthened for production security

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
        'OPTIONS': {
            'user_attributes': ('username', 'email', 'first_name', 'last_name'),
            'max_similarity': 0.7,  # Stricter similarity check
        }
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
        'OPTIONS': {
            'min_length': 12,  # Increased from default 8 to 12 characters
        }
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# Media files
# Using Cloudinary for persistent storage (Railway uses ephemeral storage)
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Cloudinary Configuration
# Get credentials from environment variables
CLOUDINARY_STORAGE = {
    'CLOUD_NAME': os.getenv('CLOUDINARY_CLOUD_NAME', ''),
    'API_KEY': os.getenv('CLOUDINARY_API_KEY', ''),
    'API_SECRET': os.getenv('CLOUDINARY_API_SECRET', ''),
}

# Storage configuration (Django 5.2+ uses STORAGES instead of deprecated DEFAULT_FILE_STORAGE)
# Uses Cloudinary for media in production, local storage in development
STORAGES = {
    "default": {
        "BACKEND": "cloudinary_storage.storage.MediaCloudinaryStorage"
        if os.getenv('CLOUDINARY_CLOUD_NAME')
        else "django.core.files.storage.FileSystemStorage",
    },
    "staticfiles": {
        "BACKEND": "django.contrib.staticfiles.storage.StaticFilesStorage",
    },
}

# Legacy setting for django-cloudinary-storage compatibility (it still checks this)
STATICFILES_STORAGE = "django.contrib.staticfiles.storage.StaticFilesStorage"

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Security Settings (per GUIDELINES.md)
# Environment-aware HTTPS enforcement: strict in production, permissive in dev
# Railway (and most platforms) terminates SSL at load balancer level
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')  # Trust X-Forwarded-Proto header
SECURE_SSL_REDIRECT = not DEBUG  # Redirect HTTP to HTTPS in production
SECURE_HSTS_SECONDS = 31536000 if not DEBUG else 0  # 1 year HSTS in production
SECURE_HSTS_INCLUDE_SUBDOMAINS = not DEBUG  # Apply HSTS to all subdomains in production
SECURE_HSTS_PRELOAD = not DEBUG  # Enable HSTS preload list in production
SECURE_CONTENT_TYPE_NOSNIFF = True  # Prevent MIME type sniffing
SECURE_BROWSER_XSS_FILTER = True  # Enable browser XSS protection
X_FRAME_OPTIONS = 'DENY'  # Prevent clickjacking
# Content Security Policy - XSS Protection
# Remove 'unsafe-inline' for production security
CSP_DEFAULT_SRC = "'self'"
CSP_IMG_SRC = "'self' data: https://picsum.photos https://ipfs.io"
CSP_SCRIPT_SRC = "'self'"  # Removed 'unsafe-inline' for security
CSP_STYLE_SRC = "'self'"   # Removed 'unsafe-inline' for security
CSP_CONNECT_SRC = "'self' wss://api.web3auth.io https://api.web3auth.io"
SECURE_REFERRER_POLICY = 'strict-origin-when-cross-origin'
SECURE_CROSS_ORIGIN_OPENER_POLICY = 'same-origin'
# No private key storage - rely on Web3Auth (FR3 in REQUIREMENTS.md)

# Placeholder for Integrations (per ARCHITECTURE.md)
# WEB3AUTH_CLIENT_ID = os.getenv('WEB3AUTH_CLIENT_ID')  # Set in env for keyless auth
# RAMP_API_KEY = os.getenv('RAMP_API_KEY')  # For fiat-to-crypto (FR2)
IPFS_API_URL = 'https://ipfs.infura.io:5001'  # Free tier for MVP (FR4)

# Future Expansion: Add moderation queue, analytics (FR7), collaboration logic (FR8)
# Ensure compliance with regulations (e.g., GDPR minimization) - no unnecessary data storage

# Web3Auth Configuration for Keyless Wallet Auth (FR3)
# SECURITY: Rotate Client ID and configure domain whitelist on Web3Auth dashboard
WEB3AUTH_CLIENT_ID = os.getenv('WEB3AUTH_CLIENT_ID', 'your_client_id_here')

# Validate Web3Auth Client ID in production
if not DEBUG and WEB3AUTH_CLIENT_ID == 'your_client_id_here':
    raise ValueError(
        'WEB3AUTH_CLIENT_ID must be set to a valid Client ID in production. '
        'Get one from https://dashboard.web3auth.io/ and configure domain whitelist.'
    )

# Prefer the auth domain JWKS for Sapphire (supports ES256)
WEB3AUTH_JWKS_URL = os.getenv('WEB3AUTH_JWKS_URL', 'https://api-auth.web3auth.io/.well-known/jwks.json')

# Web3Auth Security Best Practices:
# 1. Configure domain whitelist on Web3Auth dashboard to only allow your production domain
# 2. Use separate Client IDs for development and production
# 3. Enable session management and set appropriate timeout values
# 4. Monitor Web3Auth dashboard for suspicious activity

AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
    'allauth.account.auth_backends.AuthenticationBackend',
]

SITE_ID = 1

# django-allauth v65 settings using ACCOUNT_LOGIN_METHODS / ACCOUNT_SIGNUP_FIELDS
ACCOUNT_LOGIN_METHODS = { 'username': True }
ACCOUNT_SIGNUP_FIELDS = ['username*', 'email*', 'password1*', 'password2*']
# Ensure no other legacy flags present
try:
    del ACCOUNT_AUTHENTICATION_METHOD
    del ACCOUNT_USERNAME_REQUIRED
    del ACCOUNT_EMAIL_REQUIRED
except Exception:
    pass
ACCOUNT_EMAIL_VERIFICATION = 'none'
FRONTEND_ORIGIN = os.getenv('FRONTEND_ORIGIN', 'http://127.0.0.1:3000')
# Neutral redirects so dev works on both localhost and 127.0.0.1
LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/'

# CORS/CSRF for frontend (environment-based for production)
# In production, set CORS_ORIGINS env var to your production domain
# Example: CORS_ORIGINS=https://renaissblock.com,https://www.renaissblock.com
CORS_ORIGINS_ENV = os.getenv('CORS_ORIGINS', '')
if CORS_ORIGINS_ENV:
    # Production: use environment-specified origins
    CORS_ALLOWED_ORIGINS = [origin.strip() for origin in CORS_ORIGINS_ENV.split(',')]
    CSRF_TRUSTED_ORIGINS = [origin.strip() for origin in CORS_ORIGINS_ENV.split(',')]
elif not DEBUG:
    # Production fallback: allow production domains
    CORS_ALLOWED_ORIGINS = [
        "https://renaissblock.com",
        "https://www.renaissblock.com",
    ]
    CSRF_TRUSTED_ORIGINS = [
        "https://renaissblock.com",
        "https://www.renaissblock.com",
    ]
else:
    # Development: default to localhost
    CORS_ALLOWED_ORIGINS = [
        "http://localhost:3000",
        "http://127.0.0.1:3000",
    ]
    CSRF_TRUSTED_ORIGINS = [
        "http://localhost:3000",
        "http://127.0.0.1:3000",
    ]

# CORS settings for cross-origin requests
CORS_ALLOW_CREDENTIALS = True  # Required for cookies/sessions
CORS_ALLOW_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
]

# Session cookie settings for cross-origin auth
# For cross-origin (api.renaissblock.com -> www.renaissblock.com), use None
SESSION_COOKIE_SAMESITE = 'None' if not DEBUG else 'Lax'  # 'None' required for cross-origin
SESSION_COOKIE_SECURE = not DEBUG  # True in production (HTTPS required for SameSite=None)
SESSION_COOKIE_HTTPONLY = True  # Prevent JavaScript access (security)
SESSION_COOKIE_AGE = 86400  # 24 hours (improve security vs infinite sessions)
SESSION_SAVE_EVERY_REQUEST = True  # Extend session on activity
SESSION_COOKIE_NAME = 'rb_sessionid'  # Custom name (security through obscurity)
SESSION_COOKIE_DOMAIN = '.renaissblock.com' if not DEBUG else None  # Share across subdomains

# CSRF cookie settings for cross-origin
CSRF_COOKIE_SAMESITE = 'None' if not DEBUG else 'Lax'
CSRF_COOKIE_SECURE = not DEBUG  # True in production
CSRF_COOKIE_HTTPONLY = False  # Must be False so JavaScript can read it
CSRF_COOKIE_DOMAIN = '.renaissblock.com' if not DEBUG else None  # Share across subdomains
CSRF_COOKIE_NAME = 'rb_csrftoken'

"""Feature flags and blockchain config

Read from environment with safe defaults for MVP (SQLite). For security, do not
store private keys in the repo. Only public identifiers (program ID, pubkeys)
may be given a default here per GUIDELINES.md.
"""
FEATURE_ANCHOR_MINT = os.getenv('FEATURE_ANCHOR_MINT', 'false').lower() in ('1', 'true', 'yes', 'on')
ANCHOR_PROGRAM_ID = os.getenv('ANCHOR_PROGRAM_ID', '9ZACvfz6GNqa7fvtXTbsWUKjgzHUeJwxg4qiG8oRB7eH')
SOLANA_RPC_URL = os.getenv('SOLANA_RPC_URL', 'https://api.devnet.solana.com')
PLATFORM_WALLET_PUBKEY = os.getenv('PLATFORM_WALLET_PUBKEY', '')
# Optional: dev-only keypair path for platform wallet signer on devnet
PLATFORM_WALLET_KEYPAIR_PATH = os.getenv('PLATFORM_WALLET_KEYPAIR_PATH', '')

# Collaborative NFT Minting Configuration
SOLANA_PLATFORM_WALLET = os.getenv('SOLANA_PLATFORM_WALLET', PLATFORM_WALLET_PUBKEY or 'DawrJxixCJ2zbTCn83YRB5kZJC6zM6N36FYqGZUzNHDA')
# SOL/USD price for converting USD amounts to lamports (should use oracle in production)
SOL_PRICE_USD = os.getenv('SOL_PRICE_USD', '100.00')
# Enable collaborative minting feature
FEATURE_COLLABORATIVE_MINTING = os.getenv('FEATURE_COLLABORATIVE_MINTING', 'true').lower() in ('1', 'true', 'yes', 'on')

# Stripe Payment Configuration
STRIPE_SECRET_KEY = os.getenv('STRIPE_SECRET_KEY', '')
STRIPE_PUBLISHABLE_KEY = os.getenv('STRIPE_PUBLISHABLE_KEY', '')
STRIPE_WEBHOOK_SECRET = os.getenv('STRIPE_WEBHOOK_SECRET', '')

# Bridge.xyz Configuration (USDC -> USD Off-ramp)
# API key for Bridge.xyz - get from https://dashboard.bridge.xyz
BRIDGE_API_KEY = os.getenv('BRIDGE_API_KEY', '')
# Webhook secret for verifying Bridge webhook signatures
BRIDGE_WEBHOOK_SECRET = os.getenv('BRIDGE_WEBHOOK_SECRET', '')
# Use sandbox environment (True for testing, False for production)
BRIDGE_SANDBOX_MODE = os.getenv('BRIDGE_SANDBOX_MODE', 'true').lower() in ('1', 'true', 'yes', 'on')
# Minimum USDC amount to trigger a Bridge payout (prevents dust transactions)
BRIDGE_MIN_PAYOUT_THRESHOLD = Decimal(os.getenv('BRIDGE_MIN_PAYOUT_THRESHOLD', '10.00'))

# Platform USDC wallet address for treasury operations
# This is the Solana wallet that holds USDC treasury and fronts payments
PLATFORM_USDC_WALLET_ADDRESS = os.getenv('PLATFORM_USDC_WALLET_ADDRESS', '')

# Platform wallet for receiving secondary sale royalties (2% of resales)
# Defaults to PLATFORM_USDC_WALLET_ADDRESS if not set separately
PLATFORM_ROYALTY_WALLET_ADDRESS = os.getenv('PLATFORM_ROYALTY_WALLET_ADDRESS', PLATFORM_USDC_WALLET_ADDRESS)

# USDC Token Mint Address
# Devnet: 4zMMC9srt5Ri5X14GAgXhaHii3GnPAEERYPJgZJDncDU
# Mainnet: EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v
USDC_MINT_ADDRESS = os.getenv('USDC_MINT_ADDRESS', '4zMMC9srt5Ri5X14GAgXhaHii3GnPAEERYPJgZJDncDU')

# Solana Network
SOLANA_NETWORK = os.getenv('SOLANA_NETWORK', 'devnet')

# Pinata IPFS Configuration (for NFT metadata storage)
PINATA_JWT = os.getenv('PINATA_JWT', '')
PINATA_API_KEY = os.getenv('PINATA_API_KEY', '')
PINATA_API_SECRET = os.getenv('PINATA_API_SECRET', '')

# Application URLs for payment redirects
FRONTEND_URL = os.getenv('FRONTEND_URL', 'http://127.0.0.1:3000')
BACKEND_URL = os.getenv('BACKEND_URL', 'http://127.0.0.1:8000')

# DRF throttling for public endpoints
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.SessionAuthentication',
    ],
    'DEFAULT_THROTTLE_CLASSES': [
        'rest_framework.throttling.AnonRateThrottle',
        'rest_framework.throttling.UserRateThrottle',
    ],
    'DEFAULT_THROTTLE_RATES': {
        # General API throttles (relaxed in DEBUG for SPA polling)
        'anon': '600/min' if DEBUG else '60/min',
        'user': '600/min' if DEBUG else '120/min',
        # Strict auth endpoint throttles (prevent brute force attacks)
        'auth_anon': '10/min' if DEBUG else '5/min',
        'auth_user': '20/min' if DEBUG else '10/min',
        'signup': '5/hour' if DEBUG else '3/hour',
        'password_reset': '5/hour' if DEBUG else '3/hour',
    },
    # Custom exception handler for generic error messages in production
    'EXCEPTION_HANDLER': 'rb_core.exception_handlers.custom_exception_handler',
    # Pagination for list views (prevent DoS via large result sets)
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.LimitOffsetPagination',
    'PAGE_SIZE': 50,  # Default page size
    'MAX_PAGE_SIZE': 100,  # Maximum allowed page size
}

# Upload constraints (bytes and MIME types)
MAX_UPLOAD_BYTES = int(os.getenv('MAX_UPLOAD_BYTES', str(10 * 1024 * 1024)))  # 10 MB
ALLOWED_UPLOAD_CONTENT_TYPES = set((
    'image/jpeg', 'image/png', 'image/webp',
    'application/pdf',
    'video/mp4',
))

# Email Configuration (for beta invites and notifications)
# In development: emails are logged to console
# In beta mode: use SMTP for real email delivery
# In production: configure SMTP settings via environment variables
if BETA_MODE:
    # Beta mode: use SMTP from environment (for sending real beta invites)
    EMAIL_BACKEND = os.getenv('EMAIL_BACKEND', 'django.core.mail.backends.smtp.EmailBackend')
    EMAIL_HOST = os.getenv('EMAIL_HOST', 'smtp.gmail.com')
    EMAIL_PORT = int(os.getenv('EMAIL_PORT', '587'))
    EMAIL_USE_TLS = os.getenv('EMAIL_USE_TLS', 'True').lower() in ('true', '1', 'yes')
    EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER', '')
    EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD', '')
elif DEBUG:
    # Development: console backend
    EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
else:
    # Production: SMTP
    EMAIL_BACKEND = os.getenv('EMAIL_BACKEND', 'django.core.mail.backends.smtp.EmailBackend')
    EMAIL_HOST = os.getenv('EMAIL_HOST', 'smtp.gmail.com')
    EMAIL_PORT = int(os.getenv('EMAIL_PORT', '587'))
    EMAIL_USE_TLS = os.getenv('EMAIL_USE_TLS', 'True').lower() in ('true', '1', 'yes')
    EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER', '')
    EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD', '')

DEFAULT_FROM_EMAIL = os.getenv('DEFAULT_FROM_EMAIL', 'noreply@renaissblock.com')
ADMIN_EMAIL = os.getenv('ADMIN_EMAIL', 'admin@example.com')  # Update this to your email

# Email timeout to prevent worker hangs (Railway may block SMTP)
EMAIL_TIMEOUT = 5  # Fail quickly if SMTP is blocked

# ============================================================================
# Celery Configuration for Async Tasks
# ============================================================================
# Used for NFT minting, payment processing, and creator payouts

# Celery broker (message queue)
# For MVP: Use Redis or fallback to Django DB
CELERY_BROKER_URL = os.getenv('CELERY_BROKER_URL', 'redis://localhost:6379/0')

# Result backend (for task results)
CELERY_RESULT_BACKEND = os.getenv('CELERY_RESULT_BACKEND', 'redis://localhost:6379/0')

# Task settings
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TIMEZONE = 'UTC'
CELERY_ENABLE_UTC = True

# Task result expiration (7 days)
CELERY_RESULT_EXPIRES = 60 * 60 * 24 * 7

# Task time limits (prevent hanging tasks)
CELERY_TASK_TIME_LIMIT = 300  # 5 minutes hard limit
CELERY_TASK_SOFT_TIME_LIMIT = 240  # 4 minutes soft limit

# Task routing (future: separate queues for different task types)
CELERY_TASK_ROUTES = {
    'rb_core.tasks.mint_and_distribute': {'queue': 'minting'},
    'rb_core.tasks.schedule_creator_payout': {'queue': 'payouts'},
}

# Worker configuration
CELERY_WORKER_PREFETCH_MULTIPLIER = 1  # One task at a time for long-running mints
CELERY_WORKER_MAX_TASKS_PER_CHILD = 100  # Restart worker after 100 tasks (prevent memory leaks)

# Logging
CELERY_WORKER_HIJACK_ROOT_LOGGER = False  # Use Django logging config

## Duplicate guard: the above variables are defined once; keep this footer clean.
